### ISSUE TITLE
Regression in 1.25.2: `coreaudio.cpp: error: 'kAudioChannelLabel_LeftSideSurround' was not declared in this scope; did you mean 'kAudioChannelLabel_LeftSurround'?`

### ISSUE THREAD

**Issue by barracuda156** [kcat/openal-soft#1298]
1.25.2 does not build on 10.6:
```
[ 67%] Building CXX object CMakeFiles/OpenAL.dir/alc/backends/coreaudio.cpp.o
/opt/local/bin/g++-mp-16 -DALC_API="__attribute__((visibility(\"default\")))" -DAL_ALEXT_PROTOTYPES -DAL_API="__attribute__((visibility(\"default\")))" -DAL_BUILD_LIBRARY -DOpenAL_EXPORTS -D_GLIBCXX_ASSERTIONS=1 -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2 -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/include -F//System/Library/Frameworks -I/opt/local/var/macports/build/openal-soft-191fffec/work/build -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/common -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/gsl/include -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/fmt-11.2.0/include -pipe -Os -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -std=gnu++20 -arch ppc -mmacosx-version-min=10.6 -fPIC -fvisibility=hidden -Wunused -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wpedantic -Wformat -Wformat=2 -Wold-style-cast -Wnon-virtual-dtor -Woverloaded-virtual -Wtrampolines -Wbidi-chars=any -Wno-interference-size -Werror=undef -Werror=format-security -ftrivial-auto-var-init=pattern -fno-math-errno -MD -MT CMakeFiles/OpenAL.dir/alc/backends/coreaudio.cpp.o -MF CMakeFiles/OpenAL.dir/alc/backends/coreaudio.cpp.o.d -o CMakeFiles/OpenAL.dir/alc/backends/coreaudio.cpp.o -c /opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/alc/backends/coreaudio.cpp
[ 68%] Building CXX object CMakeFiles/OpenAL.dir/alc/backends/wave.cpp.o
/opt/local/bin/g++-mp-16 -DALC_API="__attribute__((visibility(\"default\")))" -DAL_ALEXT_PROTOTYPES -DAL_API="__attribute__((visibility(\"default\")))" -DAL_BUILD_LIBRARY -DOpenAL_EXPORTS -D_GLIBCXX_ASSERTIONS=1 -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2 -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/include -F//System/Library/Frameworks -I/opt/local/var/macports/build/openal-soft-191fffec/work/build -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/common -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/gsl/include -I/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/fmt-11.2.0/include -pipe -Os -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -std=gnu++20 -arch ppc -mmacosx-version-min=10.6 -fPIC -fvisibility=hidden -Wunused -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wpedantic -Wformat -Wformat=2 -Wold-style-cast -Wnon-virtual-dtor -Woverloaded-virtual -Wtrampolines -Wbidi-chars=any -Wno-interference-size -Werror=undef -Werror=format-security -ftrivial-auto-var-init=pattern -fno-math-errno -MD -MT CMakeFiles/OpenAL.dir/alc/backends/wave.cpp.o -MF CMakeFiles/OpenAL.dir/alc/backends/wave.cpp.o.d -o CMakeFiles/OpenAL.dir/alc/backends/wave.cpp.o -c /opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/alc/backends/wave.cpp
/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/alc/backends/coreaudio.cpp:108:5: error: 'kAudioChannelLabel_LeftSideSurround' was not declared in this scope; did you mean 'kAudioChannelLabel_LeftSurround'?
  108 |     kAudioChannelLabel_LeftSideSurround,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     kAudioChannelLabel_LeftSurround
/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/alc/backends/coreaudio.cpp:109:5: error: 'kAudioChannelLabel_RightSideSurround' was not declared in this scope; did you mean 'kAudioChannelLabel_RightSurround'?
  109 |     kAudioChannelLabel_RightSideSurround,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     kAudioChannelLabel_RightSurround
/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/alc/backends/coreaudio.cpp:110:5: error: 'kAudioChannelLabel_LeftTopFront' was not declared in this scope; did you mean 'kAudioChannelLabel_LeftTotal'?
  110 |     kAudioChannelLabel_LeftTopFront,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     kAudioChannelLabel_LeftTotal
/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/alc/backends/coreaudio.cpp:111:5: error: 'kAudioChannelLabel_RightTopFront' was not declared in this scope; did you mean 'kAudioChannelLabel_RightTotal'?
  111 |     kAudioChannelLabel_RightTopFront,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     kAudioChannelLabel_RightTotal
/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/alc/backends/coreaudio.cpp:112:5: error: 'kAudioChannelLabel_LeftTopRear' was not declared in this scope; did you mean 'kAudioChannelLabel_LeftTotal'?
  112 |     kAudioChannelLabel_LeftTopRear, kAudioChannelLabel_RightTopRear
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     kAudioChannelLabel_LeftTotal
/opt/local/var/macports/build/openal-soft-191fffec/work/openal-soft-1.25.2/alc/backends/coreaudio.cpp:112:37: error: 'kAudioChannelLabel_RightTopRear' was not declared in this scope; did you mean 'kAudioChannelLabel_RightTotal'?
  112 |     kAudioChannelLabel_LeftTopRear, kAudioChannelLabel_RightTopRear
      |                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                     kAudioChannelLabel_RightTotal

```

**Comment by barracuda156** [comment]
Introduced by https://github.com/kcat/openal-soft/commit/baa20481ea9290bdae332798e68dd1c9b6eeb0a1

**Comment by kcat** [comment]
Did these enums have different names in earlier versions, or did support for them just not exist?

**Comment by barracuda156** [comment]
@kcat Looks like they exist only in recent versions:

10.15+: https://developer.apple.com/documentation/coreaudiotypes/kaudiochannellabel_righttoprear
13+: https://developer.apple.com/documentation/coreaudiotypes/kaudiochannellabel_rightsidesurround

Not 100% sure, but I do not think there are older names for them. Likely we either need not to use them or provide definitions.
