### ISSUE TITLE
Build errors - error: invalid use of ‘this’ at top level

### ISSUE THREAD

**Issue by h1z1** [kcat/openal-soft#609]
Appears 1.21.x branches are failing to build with copious amounts of errors referring to this ?   example

```
[ 12%] Building CXX object utils/alsoft-config/CMakeFiles/alsoft-config.dir/moc_mainwindow.cpp.o
In file included from /dev/shm/build/libopenal/common/strutils.h:6:0,
                 from /dev/shm/build/libopenal/common/dynload.cpp:6:
/dev/shm/build/libopenal/common/aloptional.h:129:69: error: invalid use of ‘this’ at top level
     optional_storage& operator=(optional_storage&& rhs) NOEXCEPT_AS(this->assign(std::move(rhs)))
                                                                     ^
/dev/shm/build/libopenal/common/aloptional.h:18:45: note: in definition of macro ‘NOEXCEPT_AS’
 #define NOEXCEPT_AS(...)  noexcept(noexcept(__VA_ARGS__))
                                             ^~~~~~~~~~~
/dev/shm/build/libopenal/common/aloptional.h:139:58: error: invalid use of ‘this’ at top level
     optional_storage(optional_storage&& rhs) NOEXCEPT_AS(this->construct(std::move(rhs.mValue)))
                                                          ^
/dev/shm/build/libopenal/common/aloptional.h:18:45: note: in definition of macro ‘NOEXCEPT_AS’
 #define NOEXCEPT_AS(...)  noexcept(noexcept(__VA_ARGS__))
                                             ^~~~~~~~~~~
```

CentOS,  tried GCC 7.3.1  and 8.3.1.  No issues with openal-soft-1.21.0.*

**Comment by kcat** [comment]
Is this not an issue anymore, then?

**Comment by nimble0** [comment]
I think this is caused by a GCC bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52869

**Comment by h1z1** [comment]
> Is this not an issue anymore, then?

It's still a bug.

**Comment by kcat** [comment]
Should be fixed with commit bdc9d695.

**Comment by h1z1** [comment]
This works now (no pun intended I swear).. :)  
FWIW:

```
Words with warnings - gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
Works with warnings - gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
Works with warnings - gcc version 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC)
Fails - gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC)
```
Might be worth adding a check to cmake?

Cheers

**Comment by kcat** [comment]
I'm not sure what the actual minimum compiler version needed is, aside from "some version after GCC 4.9" (which didn't even fully support C++11). Currently it requires C++14, which it sets in CMake:
```cmake
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
```
As far as I know, GCC 5 began support for C++14, so I'd expect an error at that point with CMake if using a compiler without the necessary support.

**Comment by h1z1** [comment]
That is odd indeed...  Some C++14 support is available in gcc 4 though (through -std=c++1y)

https://gcc.gnu.org/projects/cxx-status.html#cxx14

```

$ cmake3 -B build 
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Performing Test HAVE___RESTRICT
-- Performing Test HAVE___RESTRICT - Success
-- Performing Test HAVE_LIBATOMIC
-- Performing Test HAVE_LIBATOMIC - Failed
-- Looking for __android_log_print in log
-- Looking for __android_log_print in log - not found
-- Performing Test HAVE_FNO_MATH_ERRNO
-- Performing Test HAVE_FNO_MATH_ERRNO - Success
-- Performing Test HAVE_GCC_PROTECTED_VISIBILITY
-- Performing Test HAVE_GCC_PROTECTED_VISIBILITY - Success
-- Performing Test HAVE_VISIBILITY_HIDDEN_SWITCH
-- Performing Test HAVE_VISIBILITY_HIDDEN_SWITCH - Success
-- Performing Test HAVE_MSSE2_SWITCH
-- Performing Test HAVE_MSSE2_SWITCH - Success
-- Performing Test HAVE_MSSE3_SWITCH
-- Performing Test HAVE_MSSE3_SWITCH - Success
-- Performing Test HAVE_MSSE4_1_SWITCH
-- Performing Test HAVE_MSSE4_1_SWITCH - Success
-- Performing Test HAVE_MFPU_NEON_SWITCH
-- Performing Test HAVE_MFPU_NEON_SWITCH - Failed
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Looking for pmmintrin.h
-- Looking for pmmintrin.h - found
-- Looking for smmintrin.h
-- Looking for smmintrin.h - found
-- Looking for arm_neon.h
-- Looking for arm_neon.h - not found
-- Performing Test HAVE_SSE_INTRINSICS
-- Performing Test HAVE_SSE_INTRINSICS - Success
-- Looking for malloc.h
-- Looking for malloc.h - found
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Looking for intrin.h
-- Looking for intrin.h - not found
-- Looking for guiddef.h
-- Looking for guiddef.h - not found
-- Looking for initguid.h
-- Looking for initguid.h - not found
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Performing Test HAVE_GCC_GET_CPUID
-- Performing Test HAVE_GCC_GET_CPUID - Success
-- Performing Test HAVE_STD_ALIGNED_ALLOC
-- Performing Test HAVE_STD_ALIGNED_ALLOC - Failed
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - not found
-- Looking for proc_pidpath
-- Looking for proc_pidpath - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test HAVE_PTHREAD
-- Performing Test HAVE_PTHREAD - Success
-- Looking for pthread_setschedparam
-- Looking for pthread_setschedparam - found
-- Looking for include files pthread.h, pthread_np.h
-- Looking for include files pthread.h, pthread_np.h - not found
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - not found
-- Looking for pthread_set_name_np
-- Looking for pthread_set_name_np - not found
-- Looking for getopt
-- Looking for getopt - found
-- Found ALSA: /usr/lib64/libasound.so (found version "1.1.8") 
-- Found OSS: /usr/include  
-- Could NOT find AudioIO (missing: AUDIOIO_INCLUDE_DIR) 
-- Could NOT find SoundIO (missing: SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR) 
-- Found PortAudio: /usr/lib64/libportaudio.so  
-- Found PulseAudio: /usr/lib64/libpulse.so (found version "10.0.0") 
-- Found JACK: /usr/lib64/libjack.so  
-- Could NOT find OpenSL (missing: OPENSL_LIBRARY OPENSL_INCLUDE_DIR OPENSL_ANDROID_INCLUDE_DIR) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib64/libSDL2.so  
-- Found Git: /bin/git (found version "2.22.0.214.g8dca754b1e") 
-- Found SndFile: /usr/lib64/libsndfile.so  
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1") 
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.52.102
-- Checking for module 'libavformat'
--   Found libavformat, version 58.27.103
-- Checking for module 'libavdevice'
--   Package libpostproc was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpostproc.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpostproc', required by 'libavfilter', not found
-- Checking for module 'libavutil'
--   Found libavutil, version 56.28.100
-- Checking for module 'libswscale'
--   Found libswscale, version 5.4.101
-- Checking for module 'libswresample'
--   Found libswresample, version 3.4.100
-- Checking for module 'libpostproc'
--   No package 'libpostproc' found
-- Could NOT find FFmpeg (missing: FFMPEG_INCLUDE_DIRS AVFORMAT_INCLUDE_DIRS AVCODEC_INCLUDE_DIRS AVUTIL_INCLUDE_DIRS SWSCALE_INCLUDE_DIRS SWRESAMPLE_INCLUDE_DIRS) 
-- 
Building OpenAL with support for the following backends:
     ALSA, OSS, PortAudio, PulseAudio, JACK, WaveFile, Null

Building with support for CPU extensions:
    Default, SSE, SSE2, SSE3, SSE4.1

-- Embedding HRTF datasets

-- Installing library and headers
-- Installing sample configuration
-- Installing HRTF data files
-- Installing AmbDec presets
-- 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Could NOT find MySOFA (missing: MYSOFA_LIBRARY MYSOFA_INCLUDE_DIR) 
-- Building utility programs
-- Building configuration program
-- 
-- Building example programs
-- Building SndFile example programs
-- Building SDL example programs
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /dev/shm/openal-soft/build
$  
```
