### ISSUE TITLE
error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.13 or newer

### ISSUE THREAD

**Issue by ryandesign** [kcat/openal-soft#1066]
openal-soft 1.24.0 doesn't build on macOS 10.12:

```
common/almalloc.h:78:46: error: aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.13 or newer
   78 |         return static_cast<gsl::owner<T*>>(::operator new[](n*sizeof(T), AlignVal));
      |                                              ^
common/almalloc.h:78:46: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
common/almalloc.h:81:9: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.13 or newer
   81 |     { ::operator delete[](gsl::owner<void*>{p}, AlignVal); }
      |         ^
common/almalloc.h:81:9: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
```

Full build log: https://build.macports.org/builders/ports-10.12_x86_64-builder/builds/291362/steps/install-port/logs/stdio

It builds on macOS 12 and later.

This is a regression; 1.23.1 didn't have this problem.

**Comment by kcat** [comment]
OpenAL Soft 1.24 relies on C++17. Even if those specific errors were fixed, various other structs rely on the over-alignment allocators being invoked when creating objects that have higher alignment needs. If they silently use the normal allocators without the necessary alignment, it can result in random crashes or other buggy behavior. I don't relish the idea of adding back the custom malloc functions and sprinkling in custom alignment new/delete methods, when it's been part of the standard for over 7 years. You can try using a newer compiler and static-linking the C++ runtime to avoid relying on the system having a newer libc++, but C++17 is needed for compiling.

**Comment by barracuda156** [comment]
@kcat This issue is probably unrelated to C++ standard.

**Comment by barracuda156** [comment]
@ryandesign FWIW, there is no error on 10.6 with gcc. So this looks like Apple libc++ bug.

**Comment by kcat** [comment]
> @ryandesign FWIW, there is no error on 10.6 with gcc. So this looks like Apple libc++ bug.

The issue is as the error says:
```
aligned allocation function of type 'void *(std::size_t, std::align_val_t)' is only available on macOS 10.13 or newer
```
macOS 10.12 was released on September 20, 2016, while macOS 10.13 was released on September 25, 2017, so it'd make sense that 10.13 may be needed for more complete C++17 support.

**Comment by barracuda156** [comment]
@kcat The error text is actually misleading, since here C++ runtime matters and not the macOS version. (I assumed initially that the code may use `aligned_alloc`, which _is_ dependent on macOS version, but it is not the case, as it turned out.)

**Comment by kcat** [comment]
> The error text is actually misleading, since here C++ runtime matters and not the macOS version.

Is there a way for users to upgrade the C++ runtime on their system (and developers to upgrade the compiler/system SDK) to a more modern version, without updating macOS to 10.13?  I assume 10.12 has a compiler and C++ runtime that doesn't support it, while 10.13 does. If there's no way to upgrade the C++ runtime to a sufficiently compatible version, then the runtime and macOS versions are linked.

**Comment by barracuda156** [comment]
> Is there a way for users to upgrade the C++ runtime on their system to a more modern version, without updating macOS to 10.13?

@kcat Yes, of course, there is nothing preventing someone from using a modern C++ runtime. As I notice above, everything works fine on my 10.6 (from 2008), which uses a modern `libstdc++`.

**Comment by i3roly** [comment]
ya ryry it works

**Comment by kcat** [comment]
> do you think -fno-aligned-allocation is a feasible way out for sub 10.13 systems?

I'd be surprised. There are functions that use SIMD which depend on data being 16-byte aligned (NEON is a bit more forgiving than SSE with some operations and just have less performance, but AFAIK there still are some that require alignment). Some structs have arrays that need alignment for SIMD processing, and those structs need to be allocated with the proper alignment. If the standard allocator (which typically uses `malloc`) doesn't guarantee the needed alignment, it uses the alignment-aware allocator for the given struct (which can use `std::aligned_alloc` or some other system-specific function like `posix_memalign` or `_aligned_malloc`).

The only way `-fno-aligned-allocation` can work is if the standard allocator/`malloc` actually does guarantee the needed alignment, which would make me question why it wants to use the alignment-aware allocator when it doesn't need it.

**Comment by rdb** [comment]
FWIW we are stuck on 1.23.1 for now since we currently still support down to macOS 10.13. The issue was introduced by 2f2edb326128c56e269a171961d991d8d7936e4f, could there not simply be an alternative definition of al_malloc et al when targeting older macOS versions? Something like this:
```cpp
#if defined(__APPLE__) && __MAC_OS_X_VERSION_MIN_REQUIRED < 101300
// use posix_memalign
#else
// use operator new
#endif
```

Please note also that macOS' system allocator always aligns to 16 bytes by default, so if that is the maximum needed, then a specific aligned allocation call may not be needed, though of course this may not apply to an overridden global `operator new`.

**Comment by barracuda156** [comment]
This is not a problem of macOS version, it is a problem of C++ runtime. (Yes, I understand that by default clang will use old libc++, but nevertheless, the code works on older systems when modern C++ library is used.)

**Comment by rdb** [comment]
I suppose you are suggesting to use a custom libc++ as opposed to using Apple's implementation, but to be honest, we're not prepared to build and ship a custom libc++ just so we can use a more recent OpenAL Soft version on macOS. For us it would be significantly easier to patch OpenAL Soft instead as described above, especially as we have not encountered issues with other dependencies on older macOS versions.

**Comment by kcat** [comment]
> could there not simply be an alternative definition of al_malloc et al when targeting older macOS versions?

`al_malloc` and friends has been gone for a while. The problem currently is that calling `new` will automatically generate a call to `operator new` with the `(std::size_t, std::align_val_t)` parameters when the struct/class being allocated has higher alignment requirements than what the normal `operator new` supports (what alignment that is partly depends on the implementation/target).

It might be possible to simply define custom global `void *operator new(std::size_t, std::align_val_t)`/`void operator delete(void*, std::align_val_t)` functions which use `posix_memalign` or whatever macOS supports where necessary, and hope the compiler is okay with using them instead of complaining about it even when some version of the functions are available. Though I worry if it's that easy, why doesn't it do that already? It would not be much code at all and not require any new system functionality.

The latest git version may also have other changes that older macOS versions may not like. The macos-14 CI builds were complaining about some standard ranges functionality that required bumping to macos-15 to fix (I don't know if this would affect the target macOS version, or just the version used to make the build). And newer commits use the `atomic::wait`/`atomic::notify*` functionality to avoid more costly semaphores in the mixer, which may or may not have some minimum macOS version target requirement.

**Comment by rdb** [comment]
There don't seem to be other changes necessary to get it to build targeting 10.9. I am currently building 1.24.3 using [this patch](https://raw.githubusercontent.com/rdb/panda3d-thirdparty/2b7b9d24c8106c0dcdf26e750926226ad95f8039/patches/openal-1.24.3-no-aligned-alloc.patch), which builds without diagnostics (I have yet to test whether there are issues at runtime).

It should be noted that `aligned_alloc` appears to be unavailable as well.

Defining a global operator new does sound like a better way to address this.

**Comment by rdb** [comment]
I gave it a quick go on the latest git version, but it complains about `std::to_chars` having apparently been introduced in macOS 13.3 (note that 13 != 10.13). That is _quite_ recent, being released in march 2023.

**Comment by barracuda156** [comment]
> I suppose you are suggesting to use a custom libc++ as opposed to using Apple's implementation, but to be honest, we're not prepared to build and ship a custom libc++ just so we can use a more recent OpenAL Soft version on macOS. For us it would be significantly easier to patch OpenAL Soft instead as described above, especially as we have not encountered issues with other dependencies on older macOS versions.

I agree, but this should be documented correctly, otherwise we will have a misleading precedent. I am fine with `posix_memalign` being used instead of modern C++17 version.

**Comment by kcat** [comment]
> I gave it a quick go on the latest git version, but it complains about `std::to_chars` having apparently been introduced in macOS 13.3 (note that 13 != 10.13). That is _quite_ recent, being released in march 2023.

Odd, I don't see that being used anywhere:

```
$ git grep to_chars ..
../fmt-11.2.0/ChangeLog.md:  It is even faster than `std::to_chars` from libc++ compiled with
../fmt-11.2.0/README.md:  `to_chars`, see [Speed tests](#speed-tests) and [Converting a
../fmt-11.2.0/doc/ChangeLog-old.md:  consistency with `std::format` and `std::to_chars`
../fmt-11.2.0/doc/ChangeLog-old.md:  to_chars on both libc++ and
../fmt-11.2.0/doc/api.md:  `std::to_chars` which tries to generate the smallest number of characters
```

Where does it complain about that?

**Comment by rdb** [comment]
It's apparently used by `std::format`:
```
In file included from /Users/rdb/local/src/openal-soft/al/buffer.cpp:32:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/format:211:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/format_functions.h:29:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/formatter_floating_point.h:67:30: error: 'to_chars' is unavailable: introduced in macOS 13.3
   67 |   to_chars_result __r = std::to_chars(__first, __last, __value, __fmt);
      |                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/formatter_floating_point.h:271:36: note: in instantiation of function template specialization 'std::__formatter::__to_buffer<long double>' requested here
  271 |     __result.__last = __formatter::__to_buffer(__integral, __buffer.end(), __value, chars_format::hex);
      |                                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/formatter_floating_point.h:465:25: note: in instantiation of function template specialization 'std::__formatter::__format_buffer_hexadecimal_lower_case<double, long double>' requested here
  465 |     return __formatter::__format_buffer_hexadecimal_lower_case(
      |                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/formatter_floating_point.h:658:42: note: in instantiation of function template specialization 'std::__formatter::__format_buffer<double, long double>' requested here
  658 |   __float_result __result = __formatter::__format_buffer(
      |                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/formatter_floating_point.h:764:25: note: in instantiation of function template specialization 'std::__formatter::__format_floating_point<long double, char, std::format_context>' requested here
  764 |     return __formatter::__format_floating_point(__value, __ctx, __parser_.__get_parsed_std_specifications(__ctx));
      |                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/format_functions.h:285:42: note: in instantiation of function template specialization 'std::__formatter_floating_point<char>::format<long double, std::format_context>' requested here
  285 |             __ctx.advance_to(__formatter.format(__arg, __ctx));
      |                                          ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/format_functions.h:425:15: note: in instantiation of function template specialization 'std::__vformat_to<std::back_insert_iterator<std::__format::__output_buffer<char>>, char, std::back_insert_iterator<std::__format::__output_buffer<char>>>' requested here
  425 |   return std::__vformat_to(std::move(__out_it), __fmt, __args);
      |               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/format_functions.h:455:8: note: in instantiation of function template specialization 'std::vformat_to<std::back_insert_iterator<std::__format::__output_buffer<char>>>' requested here
  455 |   std::vformat_to(__buffer.__make_output_iterator(), __fmt, __args);
      |        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__format/format_functions.h:474:15: note: in instantiation of function template specialization 'std::vformat<void>' requested here
  474 |   return std::vformat(__fmt.get(), std::make_format_args(__args...));
      |               ^
/Users/rdb/local/src/openal-soft/al/buffer.cpp:96:35: note: in instantiation of function template specialization 'std::format<int>' requested here
   96 |     throw std::runtime_error{std::format("Invalid AmbiLayout: {}",
      |                                   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk/usr/include/c++/v1/__charconv/to_chars_floating_point.h:41:1: note: 'to_chars' has been explicitly marked unavailable here
   41 | to_chars(char* __first, char* __last, long double __value, chars_format __fmt);
      | ^
10 errors generated.

```

I'm not excluding a bug in the latest macOS SDK. I don't have time to try it with an older SDK right now, perhaps I will have time to revisit this later.

**Comment by kcat** [comment]
That's quite unfortunate, I'd like to use the standard `std::format` to reduce the reliance on fmtlib (which at this point is really only needed for printing to stderr/out with UTF-8 on Windows, and for formatting ranges). If macOS 13 is needed for `std::format`, then I guess it's going to be sticking around for a while.

**Comment by kcat** [comment]
Commit 519568e28bf1317c4b49248d6d283502b4f6be10 should handle the `std::format` problem, using fmtlib again when

```c++
#if defined(__APPLE__) && __MAC_OS_X_VERSION_MIN_REQUIRED < 130000
```

is true. Let me know if that's not correct for checking the macOS target being less than 13.

**Comment by kcat** [comment]
Commits 77314a5c5df0b7289a94cd0e6b2c61fef9a0efaa and 09727fcecd6594d9b329f3eb7468eae9ae19694a try to provide replacements for the alignment-aware operator new/delete when targeting earlier than 10.13. I don't know if it'll be enough, but it's a step in the direction.

**Comment by rdb** [comment]
Thank you! Note that the requirement was 13.3, so that would have to be 130300.

You're aware that `std::format` is a C++20 feature, yes? C++20 support is unfortunately not super widespread yet, so relying on C++20 does significantly hurt portability, which is unfortunate especially for a library that is a common dependency for game engines and other middleware, since it forces all downstream users to also limit their supported platforms.

There is also some reliance on C++20 futexes (wait/notify_all) in alc/alu.cpp and al/event.cpp which require macOS 11.0, as you predicted. In Panda3D we use a custom wrapper that uses the ulock API on macOS to implement `std::atomic_(un)signed_lock_free`, see [here](https://github.com/panda3d/panda3d/blob/32bdca90150bd0e223098f59a2a86b36b7f6575f/dtool/src/dtoolbase/patomic.h#L35-L42) and [here](https://github.com/panda3d/panda3d/blob/32bdca90150bd0e223098f59a2a86b36b7f6575f/dtool/src/dtoolbase/patomic.I#L422-L479), feel free to steal that code if you wish.

fmtlib fails to compile in this instance:
```
In file included from /Users/rdb/local/src/openal-soft/examples/allafplay.cpp:83:
In file included from /Users/rdb/local/src/openal-soft/examples/common/alhelpers.hpp:13:
/Users/rdb/local/src/openal-soft/fmt-11.2.0/include/fmt/base.h:2262:45: error: implicit instantiation of undefined template 'fmt::detail::type_is_unformattable_for<ghc::filesystem::path, char>'
 2262 |     type_is_unformattable_for<T, char_type> _;
      |                                             ^
/Users/rdb/local/src/openal-soft/fmt-11.2.0/include/fmt/base.h:2235:44: note: in instantiation of function template specialization 'fmt::detail::value<fmt::context>::value<ghc::filesystem::path, 0>' requested here
 2235 |   FMT_CONSTEXPR20 FMT_INLINE value(T& x) : value(x, custom_tag()) {}
      |                                            ^
/Users/rdb/local/src/openal-soft/fmt-11.2.0/include/fmt/format.h:4201:40: note: in instantiation of function template specialization 'fmt::detail::value<fmt::context>::value<ghc::filesystem::path, 0>' requested here
 4201 |   return vformat(fmt.str, vargs<T...>{{args...}});
      |                                        ^
/Users/rdb/local/src/openal-soft/examples/allafplay.cpp:920:43: note: in instantiation of function template specialization 'fmt::format<ghc::filesystem::path &>' requested here
  920 |             throw std::runtime_error{fmt::format("Output file {} exists", outname)};
      |                                           ^
/Users/rdb/local/src/openal-soft/fmt-11.2.0/include/fmt/base.h:2102:45: note: template is declared here
 2102 | template <typename T, typename Char> struct type_is_unformattable_for;
      |                                             ^
1 error generated.
```

This patch fixes that issue:
```diff
diff --git a/examples/allafplay.cpp b/examples/allafplay.cpp
index fd671f026..e85c5b89a 100644
--- a/examples/allafplay.cpp
+++ b/examples/allafplay.cpp
@@ -917,11 +917,11 @@ try {
         auto outname = fs::path(al::char_as_u8(fname)).stem();
         outname += u8".caf";
         if(fs::exists(outname) && !fs::is_fifo(outname))
-            throw std::runtime_error{fmt::format("Output file {} exists", outname)};
+            throw std::runtime_error{fmt::format("Output file {} exists", outname.string())};
 
         renderFile.open(outname, std::ios_base::binary | std::ios_base::out);
         if(!renderFile.is_open())
-            throw std::runtime_error{fmt::format("Failed to create {}", outname)};
+            throw std::runtime_error{fmt::format("Failed to create {}", outname.string())};
 
         renderFile.write("caff", 4);
         fwrite16be(1, renderFile);
@@ -992,7 +992,7 @@ try {
         renderStart = renderFile.tellp();
         fwrite32be(0, renderFile);
 
-        fmt::println("Rendering to {}...", outname);
+        fmt::println("Rendering to {}...", outname.string());
     }
 
     while(!laf->isAtEnd())
```

After commenting out the `wait()` and `notify_all()` calls in alc/alu.cpp and al/event.cpp it compiles fine, so it appears that these are all that is needed.

Perhaps it would be useful to decide on the oldest macOS version you wish to support and set up the CI builder to target that, so you can catch these issues early? At this time we are still supporting 10.9, though I could see us moving up to 10.13 in the near future.

**Comment by barracuda156** [comment]
> Commit [519568e](https://github.com/kcat/openal-soft/commit/519568e28bf1317c4b49248d6d283502b4f6be10) should handle the `std::format` problem, using fmtlib again when
> 
> #if defined(__APPLE__) && __MAC_OS_X_VERSION_MIN_REQUIRED < 130000
> is true. Let me know if that's not correct for checking the macOS target being less than 13.

It should include `<AvailabilityMacros.h>`, and the correct macro is `MAC_OS_X_VERSION_MIN_REQUIRED` (without leading underscore).
At least in this version: https://github.com/kcat/openal-soft/blob/519568e28bf1317c4b49248d6d283502b4f6be10/common/alformat.hpp (please dismiss if already fixed).

**Comment by kcat** [comment]
> It should include `<AvailabilityMacros.h>`, and the correct macro is `MAC_OS_X_VERSION_MIN_REQUIRED` (without leading underscore).

Are you sure that's the correct macro? The `ghc_filesystem.h` header (for `std::filesystem` compatibility on older macOS) also checks `__MAC_OS_X_VERSION_MIN_REQUIRED`, as does rdb's linked patch.

**Comment by rdb** [comment]
The ones I used are a commonly used set of macros defined in Availability.h. The ones @barracuda156 refers to are a different set of macros (without the leading `__`) defined by AvailabilityMacros.h.

**Comment by barracuda156** [comment]
> > It should include `<AvailabilityMacros.h>`, and the correct macro is `MAC_OS_X_VERSION_MIN_REQUIRED` (without leading underscore).
> 
> Are you sure that's the correct macro? The `ghc_filesystem.h` header (for `std::filesystem` compatibility on older macOS) also checks `__MAC_OS_X_VERSION_MIN_REQUIRED`, as does rdb's linked patch.

Underscore-prefixed versions are from `Availability.h` which is a kinda internal header and not supposed to be used directly. It is also missing in 10.4, AFAIR.
Unless there are specific reasons to use `Availability.h` instead of `AvailabilityMacros.h`, the latter is a more robust choice.

(And there are a lot of wrong examples around, because their effects are not always obvious, they affect a subset of macOS versions and may incidentally work correctly when a missing macro expands to zero but comparison result remains valid.)

**Comment by kcat** [comment]
I see. Relatedly, then, I found this:

https://github.com/darwin-on-arm/xnu/blob/master/EXTERNAL_HEADERS/AvailabilityMacros.h

which has macros for the versions defined as values like `1040` for 10.4, rather than values like `101300` for 10.13. Are the values supposed to be different for the non-underscored macros, or is that something that changed in later SDKs?

**Comment by barracuda156** [comment]
Apple switched to six digits codes since 10.10, so those are correct: 10.5 is 1050, but 10.10 is 101000. And they work regardless of the macOS version, since they always increase together with the latter. Comparing with numerical macros is safer, since one doesn’t need to bother if they are defined.

**Comment by kcat** [comment]
Okay, I fixed the minimum version check with commit 1684a7e9d53622b976bdc4c4c29f3bb45d61265e, fixed the paths printing with commit 7cd8dd8a400881b66201b4ee3e54b9b027eae5f5, and the atomic wait/notify methods with commit 9a9fb483e53889a6d7451b290bbd48e4d804862a. How does this work out?

> You're aware that `std::format` is a C++20 feature, yes?

Yes, OpenAL Soft uses C++20 now. At least, partly. Typically, a compiler will start supporting a new standard when implementation work on new features intended for that standard begins. This lets you compile with `-std=c++2a` (or `-std=gnu++2a` as may be) before the new standard is actually done, which is good enough for CMake to enable C++20 when requested. So C++20 itself is 5 years old at this point, while CMake can enable it on compilers older than that.

From there, I can choose which features to use based on what's supported in compilers and system targets that are still relevant. I don't have to require or use all of the standard, I can either not use features that cut out too many compilers/systems that are still relevant, or use them when available and have workarounds when not (as with `std::filesystem`, which is actually a C++17 feature but there's the GHC implementation for older macOS targets that lack it), or make them completely optional (modules are a C++20 feature, but still have a ways to go for wide support; they're used in a few non-main-library things when supported, while normal headers are used when not).

**Comment by rdb** [comment]
Thank you so much! It appears to compile just fine now for macOS 10.9 and a quick test shows that playing audio still works in our engine with this build as well. :)

Perhaps a good idea to set `-DCMAKE_OSX_DEPLOYMENT_TARGET=10.9` in the CI builder?

**Comment by barracuda156** [comment]
@kcat Are `__ulock*` available on older macOS? 

I think they aren’t, and then we get a regression, since it won’t build on 10.6 anymore.

Will check soon and update on that.

**Comment by barracuda156** [comment]
@kcat `__ulock_*` are a part of private API available since 10.12: https://shift.click/blog/futex-like-apis

So https://github.com/kcat/openal-soft/commit/9a9fb483e53889a6d7451b290bbd48e4d804862a commit looks like breaking.

P. S. Or am I lacking caffeine and misreading it?

**Comment by rdb** [comment]
It can't be a regression since there's no way it was building on 10.6 before that ;-) But yes, based on a cursory look through the Darwin XNU history, it _appears_ to have been introduced around macOS 10.12. Bah. I'm going to open up a discussion on our project whether we can't raise our minimum requirement to 10.13; there is another dependency of ours that also raised their minimum to 10.13.

**Comment by barracuda156** [comment]
> It can't be a regression since there's no way it was building on 10.6 before that ;-)

As I mentioned above, it was building just fine on 10.6 with gcc 14: https://macos-powerpc.org/packages/openal-soft

> But yes, based on a cursory look through the Darwin XNU history, it _appears_ to have been introduced around macOS 10.12.

Well, then it _is_ a regression, since this topic began with a breakage on < 10.12 _for clangs,_ but now it is broken unconditionally, since instead of a runtime feature this relies on a kernel API.

> I'm going to open up a discussion on our project whether we can't raise our minimum requirement to 10.13; there is another dependency of ours that also raised their minimum to 10.13.

_It is not always necessary to follow a bad example._

But seriously speaking, isn’t it enough to state that earlier OS are not tested and not guaranteed to work? There is no reason whatsoever at the moment to actually _require_ 10.13.

**Comment by rdb** [comment]
> As I mentioned above, it was building just fine on 10.6 with gcc 14: https://macos-powerpc.org/packages/openal-soft

In that case, it would be interesting to learn how gcc implements futexes when targeting older systems (and perhaps whether these builds even work).

> Well, then it _is_ a regression, since this topic began with a breakage on < 10.12 _for clangs,_ but now it is broken unconditionally, since instead of a runtime feature this relies on a kernel API.

Fair enough.

For what it's worth, we use [a crude fallback](https://github.com/panda3d/panda3d/blob/062e3365fd2a25b10d6b839d374dc84a162f5e20/dtool/src/dtoolbase/patomic.cxx#L130-L166) based on a hash table of condition variables when futexes are not available. I would understand if such an approach may not be considered worth the effort.

> But seriously speaking, isn’t it enough to state that earlier OS are not tested and not guaranteed to work? There is no reason whatsoever at the moment to actually _require_ 10.13.

Speaking for myself, it would be helpful to have a clear statement on which versions are intended to be supported (at what level of support).

**Comment by rdb** [comment]
As an aside, I believe the 64-bit portion of the ulock API requires Darwin 19, corresponding with macOS 10.15.

**Comment by barracuda156** [comment]
> Fair enough.

If the condition is changed from APPLE to an appropriate MAC_OS_VERSION*, at least regression will be avoided. (I am not sure a special case is justified at all, since it was meant to assist earlier systems, but it can’t do that in principle, as it turned out.)

> In that case, it would be interesting to learn how gcc implements futexes

To be honest, no idea, but if we are still talking about features present in the last release, it was building without any hacks. I just dropped a fallback to an earlier version for `libstdc++`-using systems: https://github.com/macos-powerpc/powerpc-ports/blob/2de4eaef17754d33875d6a22892da440f28c8d04/audio/openal-soft/Portfile#L11
If this is something added in the master but missing in the release, then I cannot say if it builds until I try.

**Comment by kcat** [comment]
Hmm. Well, I added a 10.9 deployment target to the CI and it does build. But I guess the problem would only appear when run on an older system.

Unfortunately there doesn't seem to be any feature test macro to tell whether `atomic::wait` and friends are supported, and testing the minimum version target won't be enough if it also relies on which (version of the) STL is used. Are there any ideas for detecting when `atomic::wait` can be used, when `__ulock_*` can be used as a fallback, and when something else should be done instead?

**Comment by barracuda156** [comment]
@kcat Can `OSSpinLock` be used? That API should exist in old systems.

**Comment by rdb** [comment]
You can use `__ulock_*` conditionally by marking the symbols as weak-linked:
```cpp
extern "C" int __ulock_wait(uint32_t op, void *addr, uint64_t value, uint32_t timeout) __attribute__((weak_import));
extern "C" int __ulock_wake(uint32_t op, void *addr, uint64_t wake_value) __attribute__((weak_import));
```
And then checking `__ulock_wait != nullptr && _ulock_wake != nullptr`.

**Comment by kcat** [comment]
Commit ade218b4f7cea1ebde5a17133d7b01af41acff5b should handle missing `__ulock_` functions, and use `atomic::wait` and friends with macOS 11+.

**Comment by rdb** [comment]
Thank you so much!

**Comment by kcat** [comment]
@rdb sorry to message you like this, but do you have a method of contact so I can ask you something about the OpenAL Soft domain? I can't seem to find a method here to send a message to you directly.

**Comment by rdb** [comment]
Sure, I'll send you an email on the email address you use for your Git commits.
