### ISSUE TITLE
Build fails on Clang 14 up to 17

### ISSUE THREAD

**Issue by smallmodel** [kcat/openal-soft#1235]
When using Clang older than version 18 to build OpenAL the following errors appear:

```cmake
[1/109] Building CXX object CMakeFiles/alsoft.common.dir/common/almalloc.cpp.o
FAILED: CMakeFiles/alsoft.common.dir/common/almalloc.cpp.o
/usr/bin/clang++-15 -D_GLIBCXX_ASSERTIONS=1 -Iopenal-soft/include -Iopenal-soft/.cmake/linux-x64 -Iopenal-soft/common -Iopenal-soft/gsl/include -Iopenal-soft/fmt-11.2.0/include -O2 -g -DNDEBUG -std=gnu++20 -fPIC -fvisibility=hidden -Wunused -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wpedantic -Wformat -Wformat=2 -Wold-style-cast -Wnon-virtual-dtor -Woverloaded-virtual -Werror=undef -Werror=format-security -ftrivial-auto-var-init=pattern -fno-math-errno -pthread -MD -MT CMakeFiles/alsoft.common.dir/common/almalloc.cpp.o -MF CMakeFiles/alsoft.common.dir/common/almalloc.cpp.o.d -o CMakeFiles/alsoft.common.dir/common/almalloc.cpp.o -c openal-soft/common/almalloc.cpp
In file included from openal-soft/common/almalloc.cpp:2:
openal-soft/common/almalloc.h:116:23: error: missing 'typename' prior to dependent type name 'SP::element_type'
        using ptype = SP::element_type*;
                      ^~~~~~~~~~~~~~~~
                      typename
openal-soft/common/almalloc.h:156:23: error: missing 'typename' prior to dependent type name 'SP::element_type'
        using ptype = SP::element_type*;
                      ^~~~~~~~~~~~~~~~
                      typename
2 errors generated.
```

commands to reproduce:
```bash
sudo apt install clang-15 clang-tools-15 ninja-build
export CC=clang-15 export CXX=clang++-15
cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -B .cmake/linux-x64
cmake --build .cmake/linux-x64 --parallel --config RelWithDebInfo
```

**Comment by kcat** [comment]
Does adding the missing keyword to fix those two errors allow the build to complete? Or might there be more/other errors that also need to be fixed?

**Comment by smallmodel** [comment]
putting `typename` fix the issues, but a bunch of other errors appear such as:

```
In file included from /openal-soft/common/polyphase_resampler.cpp:2:
In file included from /openal-soft/common/polyphase_resampler.h:4:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/span:41:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/array:43:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_algobase.h:65:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/stl_iterator_base_types.h:71:
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/iterator_concepts.h:1014:13: error: no matching function for call to '__begin'
        = decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
/openal-soft/common/polyphase_resampler.cpp:161:44: note: while checking constraint satisfaction for template 'operator()<unsigned int, unsigned int &>' required here
    std::ranges::transform(std::views::iota(0u, mM), mF.begin(), [this,cutoff](u32 const i)
                                           ^
[...]
In file included from /openal-soft/common/polyphase_resampler.cpp:2:
In file included from /openal-soft/common/polyphase_resampler.h:5:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/vector:80:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/memory_resource.h:41:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/uses_allocator_args.h:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/tuple:44:
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/ranges_util.h:143:24: error: constraints not satisfied for alias template 'sentinel_t' [with _Range = std::ranges::iota_view<unsigned int, unsigned int>]
        && sized_sentinel_for<sentinel_t<_Derived>, iterator_t<_Derived>>
                              ^~~~~~~~~~~~~~~~~~~~
[...]
/openal-soft/common/polyphase_resampler.cpp:161:44: note: while checking constraint satisfaction for template 'operator()<unsigned int, unsigned int &>' required here
    std::ranges::transform(std::views::iota(0u, mM), mF.begin(), [this,cutoff](u32 const i)
                                           ^
[...]
In file included from /openal-soft/common/polyphase_resampler.cpp:2:
In file included from /openal-soft/common/polyphase_resampler.h:5:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/vector:80:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/memory_resource.h:41:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/uses_allocator_args.h:38:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/tuple:44:
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/ranges_util.h:149:24: error: constraints not satisfied for alias template 'sentinel_t' [with _Range = const std::ranges::iota_view<unsigned int, unsigned int>]
        && sized_sentinel_for<sentinel_t<const _Derived>,
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/ranges_base.h:515:12: note: because 'const std::ranges::iota_view<unsigned int, unsigned int>' does not satisfy 'range'
  template<range _Range>
           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/ranges_base.h:503:2: note: because 'ranges::begin(__t)' would be invalid: no matching function for call to object of type 'const __cust_access::_Begin'
        ranges::begin(__t);
        ^
/openal-soft/common/polyphase_resampler.cpp:161:72: error: 'cutoff' in capture list does not name a variable
    std::ranges::transform(std::views::iota(0u, mM), mF.begin(), [this,cutoff](u32 const i)
                                                                       ^
/openal-soft/common/polyphase_resampler.cpp:162:55: error: reference to local binding 'cutoff' declared in enclosing function 'PPhaseResampler::init'
    { return SincFilter(mL, beta, besseli_0_beta, mP, cutoff, i); });
                                                      ^
/openal-soft/common/polyphase_resampler.cpp:149:17: note: 'cutoff' declared here
    const auto [cutoff, width] = (mP > mQ) ? std::make_tuple(0.47 / mP, 0.03 / mP)
                ^
/openal-soft/common/polyphase_resampler.cpp:161:5: error: no matching function for call to object of type 'const std::ranges::__transform_fn'
    std::ranges::transform(std::views::iota(0u, mM), mF.begin(), [this,cutoff](u32 const i)
    ^~~~~~~~~~~~~~~~~~~~~~
[...]
```

And also:
```
In file included from /openal-soft/common/polyphase_resampler.cpp:2:
In file included from /openal-soft/common/polyphase_resampler.h:7:
/openal-soft/common/altypes.hpp:160:18: error: invalid application of 'sizeof' to an incomplete type 'i8'
        requires(sizeof(SelfType) == 2)
                 ^~~~~~~~~~~~~~~~
/openal-soft/common/altypes.hpp:545:13: note: in instantiation of template class 'al::number_base<signed char, i8>' requested here
struct i8 : al::number_base<std::int8_t, i8> { using number_base::number_base; using number_base::operator=; };
            ^
/openal-soft/common/altypes.hpp:545:8: note: definition of 'i8' is not complete until the closing '}'
struct i8 : al::number_base<std::int8_t, i8> { using number_base::number_base; using number_base::operator=; };
       ^
```
---
`gcc-12`, the latest gcc version on Ubuntu 22.04/Debian 12, compiles fine only if using the `master` branch that has the `format` include fix.
Unfortunately `clang-15` is the latest supported version on Ubuntu 22.04

**Comment by kcat** [comment]
Commit 39f06e5c1754bf106335d2a0413cf723f453e70c fixes the missing `typename`s, and commit e9c654d05f2e227f5f2011590d923a45d2119816 should fix the "invalid 'sizeof'" error. I am confused about the other errors in `polyphase_resampler.cpp`, though; it seems to be saying `std::views::iota` isn't a valid range, but it is. And it's also saying `cutoff` isn't a variable name, before pointing out where the variable was declared with that name.

**Comment by smallmodel** [comment]
`invalid sizeof` is OK now.

- Fix for typenames: [patch-typenames.patch](https://github.com/user-attachments/files/24866736/patch-typenames.patch).
- Fixes related to `overloaded` and `PairStruct` errors: [patch-struct-constructor.patch](https://github.com/user-attachments/files/24867694/patch-struct-constructor.patch)
- Fix for `clang-17`: [patch-guid-clang17.patch](https://github.com/user-attachments/files/24867613/patch-guid-clang17.patch)

The above patches fix issues for `clang-16` and `clang-17` for me, although these compilers are not supported on [Ubuntu 22.04](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md).

For `clang-14` and `clang-15`, it's the tip of the iceberg. Unfortunately C++20 support is broken on these versions. Anything that uses `std::iota` and `std::ranges::transform` / `std::ranges::copy` causes an error:

```cmake
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/iterator_concepts.h:1014:13: error: no matching function for call to '__begin'
        = decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/ranges_base.h:513:5: note: in instantiation of template type alias '__range_iter_t' requested here
    using iterator_t = std::__detail::__range_iter_t<_Tp>;
    ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/ranges_util.h:131:36: note: in instantiation of template type alias 'iterator_t' requested here
      requires contiguous_iterator<iterator_t<_Derived>>
                                   ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:2107:30: note: in instantiation of template class 'std::ranges::view_interface<std::ranges::take_view<std::span<const float, 6>>>' requested here
    class take_view : public view_interface<take_view<_Vp>>
                             ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:2298:17: note: in instantiation of template class 'std::ranges::take_view<std::span<const float, 6>>' requested here
          = requires { take_view(std::declval<_Range>(), std::declval<_Dp>()); };
                       ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:2298:17: note: in instantiation of requirement here
          = requires { take_view(std::declval<_Range>(), std::declval<_Dp>()); };
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:2298:6: note: (skipping 12 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
          = requires { take_view(std::declval<_Range>(), std::declval<_Dp>()); };
            ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:860:9: note: while substituting template arguments into constraint expression here
      = requires { std::declval<_Adaptor>()(declval<_Args>()...); };
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:885:5: note: while checking the satisfaction of concept '__adaptor_invocable<std::ranges::views::__adaptor::_Partial<std::ranges::views::_Take, int>, const std::span<const float, 6> &>' requested here
        && __adaptor_invocable<_Self, _Range>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/ranges:885:5: note: while substituting template arguments into constraint expression here
        && __adaptor_invocable<_Self, _Range>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
openal-soft/al/listener.cpp:166:32: note: while checking constraint satisfaction for template 'operator|<std::ranges::views::__adaptor::_Partial<std::ranges::views::_Take, int>, const std::span<const float, 6> &>' required here
        std::ranges::copy(vals | std::views::take(3), listener.mOrientAt.begin());
                               ^
```

This should be a good replacement (need to be done on all ranges function):
```patch
 al/listener.cpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/al/listener.cpp b/al/listener.cpp
index f639cb207..8da57bb71 100644
--- a/al/listener.cpp
+++ b/al/listener.cpp
@@ -163,8 +163,8 @@ try {
         if(!std::ranges::all_of(vals, [](float f){ return std::isfinite(f); }))
             context->throw_error(AL_INVALID_VALUE, "Listener orientation out of range");
         /* AT then UP */
-        std::ranges::copy(vals | std::views::take(3), listener.mOrientAt.begin());
-        std::ranges::copy(vals | std::views::drop(3), listener.mOrientUp.begin());
+        std::ranges::copy(vals.first(3), listener.mOrientAt.begin());
+        std::ranges::copy(vals.subspan(3, vals.size()), listener.mOrientUp.begin());
         CommitAndUpdateProps(context);
         return;
     }
```

There are also errors like these:
```cmake
/usr/bin/../lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/iterator_concepts.h:1014:13: error: no matching function for call to '__begin'
        = decltype(ranges::__cust_access::__begin(std::declval<_Tp&>()));
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
openal-soft/alc/alu.cpp:961:44: note: while checking constraint satisfaction for template 'operator()<unsigned long, unsigned int &>' required here
        for(auto const i : std::views::iota(0_uz, device->NumAuxSends))
                                           ^
```

This error disappears when removing `_uz` suffix, however it breaks with MSVC compiler.

I think some of the options could be considered:
- Maybe drop support for `clang-15` and below, which means using alternative compilers like `gcc-12` that works on Ubuntu 22.04
- Find a replacement for those functions compatible with supported compilers

**Comment by kcat** [comment]
I applied the `typename` and `overloaded`/`PairStruct` patches. The `clang-17` one can't be applied like that though, since the module file is generated using a python script with the xml "registry", so would need a change in the generator script. Does that extra `struct` keyword actually cause an error, or just a warning?

The ranges errors are a little more complicated. While the change to use `.first` and `.subspan` would work there, there are other instances of `take()` and `drop()` that rely on the implicit limiting. That is, if an array is 128 elements, and you try to `take(256)`, it will automatically clamp and give back only 128 elements, and similar for `drop(256)` automatically clamping and giving back 0 elements, while it's undefined behavior (an assertion/trap with hardening) to call `first(256)` or `subspan(256)` on a span of 128 elements.

**Comment by smallmodel** [comment]
Latest commit fix `typename` errors for clang-14 and clang-15, and `overloaded`/`PairStruct` errors for `clang-16` and `clang-17`.

For `clang-17`, that's correct, having the extra `struct` keyword in the GUID causes an error:
```cmake
openal-soft/modules/alext.cppm:845:78: error: cannot export redeclaration '_GUID' here since the previous declaration is not exported
  845 | using LPEAXSETDIRECT = auto (AL_APIENTRY*)(ALCcontext *context, const struct _GUID *property_set_id, ALuint property_id, ALuint source_id, ALvoid *value, ALuint value_size) AL_API_NOEXCEPT -> ALenum;
      |                                                                              ^
openal-soft/modules/alext.cppm:77:19: note: previous declaration is here
   77 | extern "C" struct _GUID; /* NOLINT(*-reserved-identifier) */
      |                   ^
openal-soft/modules/alext.cppm:846:78: error: cannot export redeclaration '_GUID' here since the previous declaration is not exported
  846 | using LPEAXGETDIRECT = auto (AL_APIENTRY*)(ALCcontext *context, const struct _GUID *property_set_id, ALuint property_id, ALuint source_id, ALvoid *value, ALuint value_size) AL_API_NOEXCEPT -> ALenum;
      |                                                                              ^
openal-soft/modules/alext.cppm:77:19: note: previous declaration is here
   77 | extern "C" struct _GUID; /* NOLINT(*-reserved-identifier) */
      |                   ^
2 errors generated.
```

This was [fixed](https://github.com/llvm/llvm-project/issues/98583) in `clang-19` but not backported.

It can be fixed either by removing the extra `struct`, or by exporting the `_GUID` struct earlier:
```cpp
export extern "C" struct _GUID;
```
---

For `std::iota`:
```cpp
    std::ranges::transform(std::views::iota(0u, mM), mF.begin(), [this,cutoff](u32 const i)
    { return SincFilter(mL, beta, besseli_0_beta, mP, cutoff, i); });
```

The equivalent could be:
```cpp
    std::transform(mF.cbegin(), mF.cend(), mF.begin(), [this,cutoff=cutoff,&i](const double&)
    { return SincFilter(mL, beta, besseli_0_beta, mP, cutoff, i++); });
```
(notice it fixes the lambda because it clang-15 doesn't like the tuple capture...)

For std::copy the equivalent could be:
```cpp
    std::ranges::copy(vals.first(std::min(3_uz, vals.size())), listener.mOrientAt.begin());
    std::ranges::copy(vals.subspan(std::min(3_uz, vals.size()), vals.size()), listener.mOrientUp.begin());
```

For std::transform the equivalent could be:
```cpp
    std::ranges::transform(std::span(mData.cbegin(), HilHalfSize), mData.begin(),
        [&i](const float&) -> float
```

```cpp
for(auto const idx : std::views::iota(1_uz, fftsize-1_uz))
```
The equivalent could be:
```cpp
for(size_t idx = 1_uz; idx < fftsize-1; idx++)
```

**Comment by kcat** [comment]
> For `clang-17`, that's correct, having the extra `struct` keyword in the GUID causes an error:
> [...]
> It can be fixed either by removing the extra `struct`, or by exporting the `_GUID` struct earlier:

I don't think it would be correct for the module to export `_GUID` since it doesn't "own" it. It comes from Windows' headers as part of the Windows APIs. The correct thing to do would be to include `windows.h`, but that's only for Windows and the extension is declared platform-agnostic. In either case, commit c6707cdaa51f48c897557cc7870300814e0825e7 removes the unnecessary `struct` keywords.

For the other replacements, there are alternatives to `std::views::iota`/`take`/`drop`, but they're more error prone, the reason I switched to ranges. STL ranges are used to avoid more mutable/non-const variables, and `std::views::iota` in particular ensures the index and end variables aren't erroneously modified and mess up the looping (and potentially improves optimization, since the compiler will see the index and end value can't change even if the given variables could be). `.first()` and `.subspan()` are less safe compared to `take()` and `drop()` since the former two need manual range checks (hardening stops any buffer overruns, but does so by aborting/trapping to indicate an error happened, rather than `take()` and `drop()` explicitly clamping to the range size and continuing on). I'm not very keen on the idea of switching back (specific exceptions for specific compiler problems are one thing, but I don't like having to avoid things wholesale).

**Comment by smallmodel** [comment]
Removing `struct` keyword is indeed better than exporting the `struct _GUID` as it's not part of the module.

Overall I see why C++20 is used:
https://github.com/kcat/openal-soft/blob/c311a56dd8f1f36ca07598f8efacea21d15cbb9a/alc/alconfig.cpp#L207-L209

I learned it's a lazy view to iterate and return multiple integers for `fmt::format`, it allows printing without allocating memory.
Using `clang-14`/`clang-15` would require to downgrade by temporarily allocating a vector to store all the numbers for `fmt::format`.

In the end, supporting older compilers requires too much effort and sacrifices performance. It's probably not worth the hassle as Ubuntu 22.04 will reach EOL next year (June 2027) and `gcc-12` supports it, I can live with it on my end.

Perhaps deprecate `clang-14` and `clang-15` compilers in favor of `gcc-12`? It's the minimum working replacement and the latest supported version on `ubuntu-22.04`, useful for people who use GitHub Actions to target Debian 12.

As a suggestion, compilers version could be checked through CMake:
```cmake
if((CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 16.0)
OR (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 12.0)
OR (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 19.39))
    message(FATAL_ERROR "Compiler ${CMAKE_CXX_COMPILER_ID} v${CMAKE_CXX_COMPILER_VERSION} is unsupported.\n"
                        "Requires at least GNU 12.0, Clang-16 or MSVC 2022 (build tools v14.39-17.9).")
endif()
```

(List of MSVC versions for `CMAKE_<LANG>_COMPILER_VERSION`: https://learn.microsoft.com/en-us/cpp/overview/compiler-versions)
