### ISSUE TITLE
threads.cpp uncondiotionally uses dispatch for Apple which breaks the build on systems without libdispatch

### ISSUE THREAD

**Issue by barracuda156** [kcat/openal-soft#850]
The code does not work on 10.6 for PPC:
```
[  9%] Building CXX object CMakeFiles/common.dir/common/threads.cpp.o
/opt/local/bin/g++-mp-12 -DRESTRICT=__restrict -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/build -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/include -pipe -Os -DNDEBUG -isystem/opt/local/include/LegacySupport -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -std=gnu++14 -arch ppc -mmacosx-version-min=10.6 -fPIC -fvisibility=hidden -Winline -Wunused -Wall -Wextra -Wshadow -Wconversion -Wcast-align -Wpedantic -Wold-style-cast -Wnon-virtual-dtor -Woverloaded-virtual -Wno-c++20-attribute-extensions -fno-math-errno -pthread -MD -MT CMakeFiles/common.dir/common/threads.cpp.o -MF CMakeFiles/common.dir/common/threads.cpp.o.d -o CMakeFiles/common.dir/common/threads.cpp.o -c /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp
In file included from /usr/include/dispatch/dispatch.h:59,
                 from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.h:15,
                 from /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:24:
/usr/include/dispatch/core.h:199:15: error: expected unqualified-id before '^' token
  199 | typedef void (^dispatch_block_t)(void);
      |               ^
/usr/include/dispatch/core.h:199:15: error: expected ')' before '^' token
  199 | typedef void (^dispatch_block_t)(void);
      |              ~^
      |               )
/usr/include/dispatch/core.h:236:40: error: 'dispatch_block_t' has not been declared
  236 | dispatch_async(dispatch_queue_t queue, dispatch_block_t block);
      |                                        ^~~~~~~~~~~~~~~~
/usr/include/dispatch/core.h:265:39: error: 'dispatch_block_t' has not been declared
  265 | dispatch_sync(dispatch_queue_t queue, dispatch_block_t block);
      |                                       ^~~~~~~~~~~~~~~~
/usr/include/dispatch/core.h:293:65: error: expected ')' before '^' token
  293 | dispatch_apply(dispatch_queue_t queue, size_t iterations, void (^block)(size_t));
      |                                                                ~^
      |                                                                 )
/usr/include/dispatch/core.h:293:65: error: expected ')' before '^' token
  293 | dispatch_apply(dispatch_queue_t queue, size_t iterations, void (^block)(size_t));
      |               ~                                                 ^
      |                                                                 )
/usr/include/dispatch/core.h:293:65: error: expected initializer before '^' token
In file included from /usr/include/dispatch/dispatch.h:60:
/usr/include/dispatch/events.h:104:15: error: expected unqualified-id before '^' token
  104 | typedef void (^dispatch_event_handler_t)(dispatch_event_t event);
      |               ^
/usr/include/dispatch/events.h:104:15: error: expected ')' before '^' token
  104 | typedef void (^dispatch_event_handler_t)(dispatch_event_t event);
      |              ~^
      |               )
/usr/include/dispatch/events.h:112:15: error: expected unqualified-id before '^' token
  112 | typedef void (^dispatch_source_finalizer_t)(dispatch_source_t source);
      |               ^
/usr/include/dispatch/events.h:112:15: error: expected ')' before '^' token
  112 | typedef void (^dispatch_source_finalizer_t)(dispatch_source_t source);
      |              ~^
      |               )
/usr/include/dispatch/events.h:529:9: error: 'dispatch_source_finalizer_t' has not been declared
  529 |         dispatch_source_finalizer_t finalizer);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/dispatch/events.h:610:9: error: 'dispatch_event_handler_t' has not been declared
  610 |         dispatch_event_handler_t handler);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/dispatch/events.h:660:9: error: 'dispatch_event_handler_t' has not been declared
  660 |         dispatch_event_handler_t handler);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/dispatch/events.h:776:9: error: 'dispatch_event_handler_t' has not been declared
  776 |         dispatch_event_handler_t handler);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/dispatch/events.h:821:9: error: 'dispatch_event_handler_t' has not been declared
  821 |         dispatch_event_handler_t handler);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/dispatch/events.h:909:9: error: 'dispatch_event_handler_t' has not been declared
  909 |         dispatch_event_handler_t handler);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/dispatch/events.h:985:9: error: 'dispatch_event_handler_t' has not been declared
  985 |         dispatch_event_handler_t handler);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/dispatch/events.h:1056:9: error: 'dispatch_event_handler_t' has not been declared
 1056 |         dispatch_event_handler_t handler);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.h:28:25: error: 'dispatch_semaphore_t' does not name a type; did you mean 'dispatch_source_t'?
   28 |     using native_type = dispatch_semaphore_t;
      |                         ^~~~~~~~~~~~~~~~~~~~
      |                         dispatch_source_t
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.h:32:5: error: 'native_type' does not name a type
   32 |     native_type mSem;
      |     ^~~~~~~~~~~
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp: In constructor 'al::semaphore::semaphore(unsigned int)':
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:144:5: error: 'mSem' was not declared in this scope
  144 |     mSem = dispatch_semaphore_create(initial);
      |     ^~~~
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:144:12: error: 'dispatch_semaphore_create' was not declared in this scope; did you mean 'dispatch_source_read_create'?
  144 |     mSem = dispatch_semaphore_create(initial);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
      |            dispatch_source_read_create
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp: In destructor 'al::semaphore::~semaphore()':
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:150:20: error: 'mSem' was not declared in this scope
  150 | { dispatch_release(mSem); }
      |                    ^~~~
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:150:3: error: 'dispatch_release' was not declared in this scope; did you mean 'dispatch_queue_s'?
  150 | { dispatch_release(mSem); }
      |   ^~~~~~~~~~~~~~~~
      |   dispatch_queue_s
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp: In member function 'void al::semaphore::post()':
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:153:29: error: 'mSem' was not declared in this scope
  153 | { dispatch_semaphore_signal(mSem); }
      |                             ^~~~
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:153:3: error: 'dispatch_semaphore_signal' was not declared in this scope
  153 | { dispatch_semaphore_signal(mSem); }
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp: In member function 'void al::semaphore::wait()':
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:156:27: error: 'mSem' was not declared in this scope
  156 | { dispatch_semaphore_wait(mSem, DISPATCH_TIME_FOREVER); }
      |                           ^~~~
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:156:33: error: 'DISPATCH_TIME_FOREVER' was not declared in this scope; did you mean 'DISPATCH_TIMER_ONESHOT'?
  156 | { dispatch_semaphore_wait(mSem, DISPATCH_TIME_FOREVER); }
      |                                 ^~~~~~~~~~~~~~~~~~~~~
      |                                 DISPATCH_TIMER_ONESHOT
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:156:3: error: 'dispatch_semaphore_wait' was not declared in this scope
  156 | { dispatch_semaphore_wait(mSem, DISPATCH_TIME_FOREVER); }
      |   ^~~~~~~~~~~~~~~~~~~~~~~
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp: In member function 'bool al::semaphore::try_wait()':
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:159:34: error: 'mSem' was not declared in this scope
  159 | { return dispatch_semaphore_wait(mSem, DISPATCH_TIME_NOW) == 0; }
      |                                  ^~~~
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:159:40: error: 'DISPATCH_TIME_NOW' was not declared in this scope; did you mean 'DISPATCH_TIMER_ONESHOT'?
  159 | { return dispatch_semaphore_wait(mSem, DISPATCH_TIME_NOW) == 0; }
      |                                        ^~~~~~~~~~~~~~~~~
      |                                        DISPATCH_TIMER_ONESHOT
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/openal-soft-1.23.0/common/threads.cpp:159:10: error: 'dispatch_semaphore_wait' was not declared in this scope
  159 | { return dispatch_semaphore_wait(mSem, DISPATCH_TIME_NOW) == 0; }
      |          ^~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-c++20-attribute-extensions' may have been intended to silence earlier diagnostics
make[2]: *** [CMakeFiles/common.dir/common/threads.cpp.o] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal-soft/openal-soft/work/build'
make[1]: *** [CMakeFiles/common.dir/all] Error 2
```
This also cannot possibly work on 10.5.8, which does not have `libdispatch` at all.

We need a fallback, whether Apple-specific or likely a generic Unix one.

**Comment by halx99** [comment]
@kcat this patch cause ios crash at sem_init fail with errno=78 (function not implemented)

**Comment by barracuda156** [comment]
@halx99 Could you suggest how to fix that, without breaking what we fixed in the patch? I can test then to make sure it also works on 10.5–10.6. (I cannot test iOS though.)

**Comment by halx99** [comment]
> @halx99 Could you suggest how to fix that, without breaking what we fixed in the patch? I can test then to make sure it also works on 10.5–10.6. (I cannot test iOS though.)

I create a PR #855 to fix the issue
