### ISSUE TITLE
error: member reference base type 'al::span' is not a structure or union

### ISSUE THREAD

**Issue by ryandesign** [kcat/openal-soft#1064]
openal-soft 1.24.0 doesn't build on macOS 10.15:

```
alc/alu.cpp:2148:9: error: member reference base type 'al::span' is not a structure or union
        .subspan(Offset*FrameStep);
        ^~~~~~~~
alc/alu.cpp:2179:79: error: member reference base type 'al::span' is not a structure or union
        const auto dst = al::span{static_cast<T*>(dstbuf), Offset+SamplesToDo}.subspan(Offset);
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
```

Full build log: https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/200661/steps/install-port/logs/stdio

It builds on macOS 12 and later.

This is a regression; 1.23.1 didn't have this problem.

**Comment by kcat** [comment]
Not sure why this is failing. It seems to not recognize `al::span{...}` as creating a span object on those lines, but similar lines like `al::span{*srcbuf}.first(SamplesToDo)` right above the latter on line 2178 doesn't result in an error. Might need a newer compiler with better C++17 conformance.

**Comment by ACrazyTown** [comment]
Also seeing this issue trying to build for Android on Ubuntu 20.04.6: https://github.com/ACrazyTown/lime/actions/runs/12120772792/job/33790212432#step:11:29679

**Comment by kcat** [comment]
What compiler version is that using?

**Comment by ACrazyTown** [comment]
> What compiler version is that using?

clang version 11.0.0-2~ubuntu20.04.1

**Comment by kcat** [comment]
That is weird, that version of Clang seems like it should be fine for C++17 core language features (according to [cppreference](https://en.cppreference.com/w/cpp/compiler_support/17)). Can you try with commit 808bb2269ac8eb64ff5fbc030525740f003feb7a, which tries to break up the statement and use a proper variable instead of acting on the temporary.

**Comment by ACrazyTown** [comment]
> That is weird, that version of Clang seems like it should be fine for C++17 core language features (according to [cppreference](https://en.cppreference.com/w/cpp/compiler_support/17)). Can you try with commit [808bb22](https://github.com/kcat/openal-soft/commit/808bb2269ac8eb64ff5fbc030525740f003feb7a), which tries to break up the statement and use a proper variable instead of acting on the temporary.

I think that fixed it, now it's erroring in a different position that does the same thing:
```
./lib/openal/core/uhjfilter.cpp:219:39: error: member reference base type 'al::span' is not a structure or union
        auto wxio = al::span{mWXInOut}.subspan(mFifoPos, todo);
                    ~~~~~~~~~~~~~~~~~~^~~~~~~~
1 error generated.
```

**Comment by kcat** [comment]
Commit 5050d34920e8426d6f1c569567e94c45d2a9400f should handle that one.

**Comment by ACrazyTown** [comment]
> Commit [5050d34](https://github.com/kcat/openal-soft/commit/5050d34920e8426d6f1c569567e94c45d2a9400f) should handle that one.

That seems to have fixed it, thank you very much!

**Comment by barracuda156** [comment]
@ryandesign Could you confirm if this is fixed for affected systems with clangs?

**Comment by ryandesign** [comment]
> @ryandesign Could you confirm if this is fixed for affected systems with clangs?

It is not fixed. Here is a new build log of 1.24.1 on macOS 10.15:

https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/202320/steps/install-port/logs/stdio

**Comment by ryandesign** [comment]
Oh, 1.24.1 didn't include the fixes. Let me try applying the above-mentioned commits.

**Comment by kcat** [comment]
> It is not fixed. Here is a new build log of 1.24.1 on macOS 10.15:

That's using the same 1.24.1 release code. You'll need to pull a more recent master to get the fixes, or try to manually apply commit 808bb2269ac8eb64ff5fbc030525740f003feb7a and 5050d34920e8426d6f1c569567e94c45d2a9400f.

**Comment by ryandesign** [comment]
Yes, with those patches added on to 1.24.1 it does build on macOS 10.15 with Apple clang version 11.0.3 (clang-1103.0.32.62) from Xcode 11.7; thanks.

https://build.macports.org/builders/ports-10.15_x86_64-builder/builds/202321/steps/install-port/logs/stdio

**Comment by barracuda156** [comment]
@ryandesign If aligned allocation issue is solved for clangs, the main port can be updated to 1.24.1 across the board. I am not sure re 10.5 at the moment, but there 1.23.1 is also broken (same Core Audio issue), so not a stopper. 10.6 ppc builds fine, so everything later should be fine too.

**Comment by ryandesign** [comment]
> aligned allocation issue

This issue is not about aligned allocation; #1066 is.
