### ISSUE TITLE
Minimum compiler version for the latest OpenAl

### ISSUE THREAD

**Issue by minghia** [kcat/openal-soft#347]
What is the minimum version of gcc that is required to compile OpenAl-soft?

**Comment by kcat** [comment]
As of the current master, GCC 5 is the minimum. GCC 5.4 for sure works as its part of the CI setup, though if an earlier 5.x version fails I can take a look and try to fix it.

**Comment by minghia** [comment]
We have 4.9.4 on our machine and compiling 1.20 was a no show. The version I got to work was 1.15.1. Is there any reason to go to the latest and greatest, apart from possible bug fixes?

**Comment by kcat** [comment]
Aside from bug fixes, there's also have better compatibility, performance, and features. Newer versions interact with the system better, have more optimized routines, and have better options for resampling, panning, etc. Effect processing has also been improved to work better with surround sound and HRTF.

**Comment by minghia** [comment]
I tried to compile with 6.3.1 and got the following error messages:

`[  0%] Built target build_version
[  1%] Built target native-tools
[ 12%] Built target common
[ 13%] Building CXX object CMakeFiles/OpenAL.dir/alc/alc.cpp.o
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:52:0,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/stdexcept:39,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/array:39,
                 from /home/avasile/src/openal-soft/alc/alc.cpp:27:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h: In instantiation of ‘class std::basic_string<char, std::char_traits<char>, al::allocator<char, 1ul> >’:
/home/avasile/src/openal-soft/alc/alc.cpp:806:12:   required from here
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2623:57: error: no type named ‘size_type’ in ‘std::basic_string<char, std::char_traits<char>, al::allocator<char, 1ul> >::_CharT_alloc_type {aka struct al::allocator<char, 1ul>}’
       typedef typename _CharT_alloc_type::size_type     size_type;
                                                         ^~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2624:61: error: no type named ‘difference_type’ in ‘std::basic_string<char, std::char_traits<char>, al::allocator<char, 1ul> >::_CharT_alloc_type {aka struct al::allocator<char, 1ul>}’
       typedef typename _CharT_alloc_type::difference_type   difference_type;
                                                             ^~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2625:57: error: no type named ‘reference’ in ‘std::basic_string<char, std::char_traits<char>, al::allocator<char, 1ul> >::_CharT_alloc_type {aka struct al::allocator<char, 1ul>}’
       typedef typename _CharT_alloc_type::reference     reference;
                                                         ^~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2626:61: error: no type named ‘const_reference’ in ‘std::basic_string<char, std::char_traits<char>, al::allocator<char, 1ul> >::_CharT_alloc_type {aka struct al::allocator<char, 1ul>}’
       typedef typename _CharT_alloc_type::const_reference   const_reference;
                                                             ^~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2627:55: error: no type named ‘pointer’ in ‘std::basic_string<char, std::char_traits<char>, al::allocator<char, 1ul> >::_CharT_alloc_type {aka struct al::allocator<char, 1ul>}’
       typedef typename _CharT_alloc_type::pointer     pointer;
                                                       ^~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2628:61: error: no type named ‘const_pointer’ in ‘std::basic_string<char, std::char_traits<char>, al::allocator<char, 1ul> >::_CharT_alloc_type {aka struct al::allocator<char, 1ul>}’
       typedef typename _CharT_alloc_type::const_pointer     const_pointer;
                                                             ^~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2629:68: error: no type named ‘pointer’ in ‘using other = struct al::allocator<char, 1ul> {aka struct al::allocator<char, 1ul>}’
       typedef __gnu_cxx::__normal_iterator<pointer, basic_string>  iterator;
                                                                    ^~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2631:61: error: no type named ‘const_pointer’ in ‘using other = struct al::allocator<char, 1ul> {aka struct al::allocator<char, 1ul>}’
                                                             const_iterator;
                                                             ^~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2632:53: error: no type named ‘const_pointer’ in ‘using other = struct al::allocator<char, 1ul> {aka struct al::allocator<char, 1ul>}’
       typedef std::reverse_iterator<const_iterator> const_reverse_iterator;
                                                     ^~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:2633:52: error: no type named ‘pointer’ in ‘using other = struct al::allocator<char, 1ul> {aka struct al::allocator<char, 1ul>}’
       typedef std::reverse_iterator<iterator>      reverse_iterator;
                                                    ^~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h: In instantiation of ‘std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::append(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]’:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3503:32:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::operator+=(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]’
/home/avasile/src/openal-soft/alc/alc.cpp:962:22:   required from here
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3570:51: error: no matching function for call to ‘std::basic_string<char, std::char_traits<char>, al::allocator<char, 1ul> >::append(const char*&, std::size_t)’
  return this->append(__s, traits_type::length(__s));
                                                   ^
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:53:0,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/stdexcept:39,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/array:39,
                 from /home/avasile/src/openal-soft/alc/alc.cpp:27:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:764:5: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::append(const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]
     basic_string<_CharT, _Traits, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:764:5: note:   candidate expects 1 argument, 2 provided
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:52:0,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/stdexcept:39,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/array:39,
                 from /home/avasile/src/openal-soft/alc/alc.cpp:27:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3567:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::append(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]
       append(const _CharT* __s)
       ^~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3567:7: note:   candidate expects 1 argument, 2 provided
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3591:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::append(std::initializer_list<_Tp>) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]
       append(initializer_list<_CharT> __l)
       ^~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3591:7: note:   candidate expects 1 argument, 2 provided
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3605:9: note: candidate: template<class _InputIterator> std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::append(_InputIterator, _InputIterator) [with _InputIterator = _InputIterator; _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]
         append(_InputIterator __first, _InputIterator __last)
         ^~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3605:9: note:   template argument deduction/substitution failed:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3570:51: note:   deduced conflicting types for parameter ‘_InputIterator’ (‘const char*’ and ‘long unsigned int’)
  return this->append(__s, traits_type::length(__s));
                                                   ^
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h: In instantiation of ‘std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]’:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3093:32:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::operator=(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]’
/home/avasile/src/openal-soft/alc/alc.cpp:2676:65:   required from here
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3693:51: error: no matching function for call to ‘std::basic_string<char, std::char_traits<char>, al::allocator<char, 1ul> >::assign(const char*&, std::size_t)’
  return this->assign(__s, traits_type::length(__s));
                                                   ^
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:53:0,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/stdexcept:39,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/array:39,
                 from /home/avasile/src/openal-soft/alc/alc.cpp:27:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:682:5: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::assign(const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]
     basic_string<_CharT, _Traits, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.tcc:682:5: note:   candidate expects 1 argument, 2 provided
In file included from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/string:52:0,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/stdexcept:39,
                 from /opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/array:39,
                 from /home/avasile/src/openal-soft/alc/alc.cpp:27:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3641:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::assign(std::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]
       assign(basic_string&& __str)
       ^~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3641:7: note:   candidate expects 1 argument, 2 provided
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3690:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]
       assign(const _CharT* __s)
       ^~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3690:7: note:   candidate expects 1 argument, 2 provided
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3719:9: note: candidate: template<class _InputIterator> std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::assign(_InputIterator, _InputIterator) [with _InputIterator = _InputIterator; _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]
         assign(_InputIterator __first, _InputIterator __last)
         ^~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3719:9: note:   template argument deduction/substitution failed:
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3693:51: note:   deduced conflicting types for parameter ‘_InputIterator’ (‘const char*’ and ‘long unsigned int’)
  return this->assign(__s, traits_type::length(__s));
                                                   ^
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3729:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::assign(std::initializer_list<_Tp>) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = al::allocator<char, 1ul>]
       assign(initializer_list<_CharT> __l)
       ^~~~~~
/opt/rh/devtoolset-6/root/usr/include/c++/6.3.1/bits/basic_string.h:3729:7: note:   candidate expects 1 argument, 2 provided
CMakeFiles/OpenAL.dir/build.make:204: recipe for target 'CMakeFiles/OpenAL.dir/alc/alc.cpp.o' failed
make[2]: *** [CMakeFiles/OpenAL.dir/alc/alc.cpp.o] Error 1
CMakeFiles/Makefile2:253: recipe for target 'CMakeFiles/OpenAL.dir/all' failed
make[1]: *** [CMakeFiles/OpenAL.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`

I would have tried 5 but that would have required me to build the compiler myself and I didn't have the time.

**Comment by kcat** [comment]
Can you try the latest master? Seems GCC 6.3 is relying on some allocator fields that are supposed to be optional, but I've added them now to hopefully satisfy it.

**Comment by minghia** [comment]
It worked but alrecord and altonegen require -lrt on Centos 6.10 to link. I couldn't work out which cmake value to add this to so I manually updated the appropriate link.txt file and just ran it.

**Comment by minghia** [comment]
By the way the version string for the master release is set to 1.19.1. Is this correct?

**Comment by kcat** [comment]
> By the way the version string for the master release is set to 1.19.1. Is this correct?

Yes, the version number is updated for the release, so current master has the current release version until then (the trace log contains the commit ID, so it can be correctly identified).
