### ISSUE TITLE
1.23.0: no longer builds on Debian 10 with GCC 8.3

### ISSUE THREAD

**Issue by koprok** [kcat/openal-soft#828]
Building openal-soft 1.23.0 on Debian 10 using the default compiler GCC 8.3 fails. It looks that the newly added `[[likely]]` and `[[unlikely]]` attributes are not well supported by this GCC version. There are a lot of errors and warnings similar to:
```
common/alcomplex.cpp:104:42: warning: attributes at the beginning of statement are ignored [-Wattributes]
     if(log2_size >= gBitReverses.size()) [[unlikely]]
                                          ^
common/alcomplex.cpp:119:52: error: expected identifier before ‘[’ token
     else for(auto &rev : gBitReverses[log2_size]) [[likely]]
                                                    ^
```
FYI, openal-soft 1.22 used to work fine on Debian 10.
Also openal-soft 1.23 works fine on (newer) Debian 11 with (newer) GCC 10.2.

**Comment by kcat** [comment]
Does it build with commit 8e5db6e50599b826a41c1fadcc0b121dff0a6f17? It won't get rid of the warnings, but that error should be fixed.

**Comment by kcat** [comment]
Hmm, I don't see what's different about the remaining ones, if it doesn't error after the `if`s like in that log snippet. The C++ standard says the compiler should ignore unknown/unsupported attributes (as it does with the first one, despite warning about it), and as that's a valid place to put an attribute, it's undoubtedly a compiler bug to error with the second one. I didn't want to have to hide standard attributes behind macros, but I may have to if GCC won't fix that bug for the 8.x branch.

**Comment by koprok** [comment]
You are right, it is strange that the attributes are accepted in once place but not in another. But even if GCC fixes this in 8.x branch, I doubt Debian will update the compiler. It may even be fixed in GCC already - GCC 8.3 is not the latest release in the 8.x branch (I think 8.4 is the latest).
Unfortunately, if you want to support these older compilers / Linux distros, macros are the only way. Debian 10 is not that much old too.
Please, let me know if I can help with something (other than testing on Debian 10) to solve this?

**Comment by bibendovsky** [comment]
In the "Explanation" section on [this page](https://en.cppreference.com/w/cpp/language/attributes) it stated that ignore-unknown-attributes-without-error behavior available since C++17:

'All attributes unknown to an implementation are ignored without causing an error. (since C++17)'

**Comment by kcat** [comment]
> In the "Explanation" section on [this page](https://en.cppreference.com/w/cpp/language/attributes) it stated that ignore-unknown-attributes-without-error behavior available since C++17:

Yes, though compilers have largely been doing that anyway. The problem here isn't that the attribute itself is causing an error, but that the compiler's parser didn't expect an attribute there (it would fail equally for any attribute).

**Comment by koprok** [comment]
@bibendovsky, for the experiment, I have tried to change the required C++ standard in `CMakeLists.txt` from 14 to 17 (the `CMAKE_CXX_STANDARD` variable). The same errors happen. So it looks to me like these attributes are just not yet supported in GCC 8.3, given that C++17 support is still marked as "experimental" in GCC 8.3.

**Comment by koprok** [comment]
@kcat, you are right probably, about the parser. But I don't get what exactly is supported and what is not. If I remove the attribute from alcomplex.cpp:119, the next error I get is:
```
common/intrusive_ptr.h:21:23: error: expected identifier before ‘[’ token
         if(ref == 0) [[unlikely]]
                       ^
```
I don't see how this is different from alcomplex.cpp:104 - where there is only a warning instead of error.
So, I think it will be best to hide these attributes behind macros.

**Comment by kcat** [comment]
It looks like it's influenced by what comes after the attribute. Playing around a little with Compiler Explorer, this works in GCC 8 (with the same warning as in the first post):
```c++
if(r == 1) [[unlikely]]
    return r;
return r-1;
```
while this fails (with the same error as in the first post):
```c++
if(r == 1) [[unlikely]]
    delete ptr;
return r-1;
```
It fails with GCC 8.3, 8.4, and 8.5. It works with GCC 9.1 (CE doesn't seem to list 9.0).

This should be fixed with commit fde74453a62a1ce4b5efaac0ec1835b9f5731e25, which put the attributes behind macros. That should also cut down on warnings from them with older compilers.

**Comment by koprok** [comment]
@kcat , I have tested commit fde74453a62a1ce4b5efaac0ec1835b9f5731e25 and it fixes the build with GCC 8.3. Thank you very much for your quick response!
