### ISSUE TITLE
Cannot compile on macOS: error: use of undeclared identifier 'aligned_alloc'

### ISSUE THREAD

**Issue by hoechenberger** [kcat/openal-soft#311]
When trying to compile on macOS 10.14.5 with the latest XCode command line tools installed, I get the following error:
```
$ make
Scanning dependencies of target native-tools
[  1%] Generating native-tools/bin2h, native-tools/bsincgen
-- The C compiler identification is AppleClang 11.0.0.11000020
-- The CXX compiler identification is AppleClang 11.0.0.11000020
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pow in m
-- Looking for pow in m - found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hoechenberger/Development/openal-soft/build/native-tools
Scanning dependencies of target bsincgen
[ 25%] Building C object CMakeFiles/bsincgen.dir/bsincgen.c.o
[ 50%] Linking C executable bsincgen
[ 50%] Built target bsincgen
Scanning dependencies of target bin2h
[ 75%] Building C object CMakeFiles/bin2h.dir/bin2h.c.o
[100%] Linking C executable bin2h
[100%] Built target bin2h
[  1%] Built target native-tools
Scanning dependencies of target build_version
[  1%] Built target build_version
[  2%] Generating bsinc_inc.h
[  4%] Generating default-44100.mhr.h
[  5%] Generating default-48000.mhr.h
Scanning dependencies of target OpenAL
[  7%] Building CXX object CMakeFiles/OpenAL.dir/common/alcomplex.cpp.o
[  8%] Building CXX object CMakeFiles/OpenAL.dir/common/alexcpt.cpp.o
[ 10%] Building CXX object CMakeFiles/OpenAL.dir/common/almalloc.cpp.o
/Users/hoechenberger/Development/openal-soft/common/almalloc.cpp:27:12: error: use of undeclared identifier 'aligned_alloc'
    return aligned_alloc(alignment, size);
           ^
1 error generated.
make[2]: *** [CMakeFiles/OpenAL.dir/common/almalloc.cpp.o] Error 1
make[1]: *** [CMakeFiles/OpenAL.dir/all] Error 2
make: *** [all] Error 2
```
Compiler info:
```
$ clang --version
Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Any help and suggestions would be greatly appreciated.

**Comment by kcat** [comment]
Can you paste the output of a fresh cmake run (from an empty build directory)? It appears cmake found `aligned_alloc` (C11 standard), but while actually building the lib, the compiler can't find it anymore.

**Comment by hoechenberger** [comment]
> Can you paste the output of a fresh cmake run (from an empty build directory)?

Sure,  sorry I forgot to include this in my initial report!

<details>
  <summary>cmake output</summary>
```
$ rm -rf build && mkdir build && cd build
$ cmake ..
-- The C compiler identification is AppleClang 11.0.0.11000020
-- The CXX compiler identification is AppleClang 11.0.0.11000020
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Performing Test HAVE_STD_C11
-- Performing Test HAVE_STD_C11 - Success
-- Performing Test HAVE_STD_CXX11
-- Performing Test HAVE_STD_CXX11 - Success
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Checking _FILE_OFFSET_BITS for large files
-- Checking _FILE_OFFSET_BITS for large files - not needed
-- Performing Test HAVE___RESTRICT
-- Performing Test HAVE___RESTRICT - Success
-- Performing Test HAVE_LIBATOMIC
-- Performing Test HAVE_LIBATOMIC - Failed
-- Looking for __android_log_print in log
-- Looking for __android_log_print in log - not found
-- Performing Test HAVE_W_EXTRA
-- Performing Test HAVE_W_EXTRA - Success
-- Performing Test HAVE_FNO_MATH_ERRNO
-- Performing Test HAVE_FNO_MATH_ERRNO - Success
-- Performing Test HAVE_GCC_DESTRUCTOR
-- Performing Test HAVE_GCC_DESTRUCTOR - Success
-- Performing Test HAVE_GCC_PROTECTED_VISIBILITY
-- Performing Test HAVE_GCC_PROTECTED_VISIBILITY - Failed
-- Performing Test HAVE_GCC_DEFAULT_VISIBILITY
-- Performing Test HAVE_GCC_DEFAULT_VISIBILITY - Success
-- Performing Test HAVE_VISIBILITY_HIDDEN_SWITCH
-- Performing Test HAVE_VISIBILITY_HIDDEN_SWITCH - Success
-- Performing Test HAVE_MSSE2_SWITCH
-- Performing Test HAVE_MSSE2_SWITCH - Success
-- Performing Test HAVE_MSSE3_SWITCH
-- Performing Test HAVE_MSSE3_SWITCH - Success
-- Performing Test HAVE_MSSE4_1_SWITCH
-- Performing Test HAVE_MSSE4_1_SWITCH - Success
-- Performing Test HAVE_MFPU_NEON_SWITCH
-- Performing Test HAVE_MFPU_NEON_SWITCH - Success
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Looking for pmmintrin.h
-- Looking for pmmintrin.h - found
-- Looking for smmintrin.h
-- Looking for smmintrin.h - found
-- Looking for arm_neon.h
-- Looking for arm_neon.h - not found
-- Performing Test HAVE_SSE_INTRINSICS
-- Performing Test HAVE_SSE_INTRINSICS - Success
-- Performing Test HAVE_GCC_FORMAT
-- Performing Test HAVE_GCC_FORMAT - Success
-- Looking for malloc.h
-- Looking for malloc.h - not found
-- Looking for dirent.h
-- Looking for dirent.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Looking for intrin.h
-- Looking for intrin.h - not found
-- Looking for sys/sysconf.h
-- Looking for sys/sysconf.h - not found
-- Looking for fenv.h
-- Looking for fenv.h - found
-- Looking for float.h
-- Looking for float.h - found
-- Looking for ieeefp.h
-- Looking for ieeefp.h - not found
-- Looking for guiddef.h
-- Looking for guiddef.h - not found
-- Looking for initguid.h
-- Looking for initguid.h - not found
-- Looking for pow in m
-- Looking for pow in m - found
-- Looking for dlopen in dl
-- Looking for dlopen in dl - found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Performing Test HAVE_GCC_GET_CPUID
-- Performing Test HAVE_GCC_GET_CPUID - Success
-- Looking for sysconf
-- Looking for sysconf - found
-- Looking for aligned_alloc
-- Looking for aligned_alloc - found
-- Looking for posix_memalign
-- Looking for posix_memalign - found
-- Looking for _aligned_malloc
-- Looking for _aligned_malloc - not found
-- Looking for proc_pidpath
-- Looking for proc_pidpath - found
-- Looking for stat
-- Looking for stat - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for windows.h
-- Looking for windows.h - not found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for include files pthread.h, pthread_np.h
-- Looking for include files pthread.h, pthread_np.h - not found
-- Performing Test HAVE_PTHREAD
-- Performing Test HAVE_PTHREAD - Success
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for pthread_setschedparam
-- Looking for pthread_setschedparam - found
-- Looking for pthread_setname_np
-- Looking for pthread_setname_np - found
-- Performing Test PTHREAD_SETNAME_NP_ONE_PARAM
-- Performing Test PTHREAD_SETNAME_NP_ONE_PARAM - Success
-- Performing Test PTHREAD_SETNAME_NP_THREE_PARAMS
-- Performing Test PTHREAD_SETNAME_NP_THREE_PARAMS - Failed
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
-- Looking for getopt
-- Looking for getopt - found
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR)
-- Could NOT find OSS (missing: OSS_INCLUDE_DIR)
-- Could NOT find AudioIO (missing: AUDIOIO_INCLUDE_DIR)
-- Could NOT find SoundIO (missing: SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR)
-- Could NOT find QSA (missing: QSA_LIBRARY QSA_INCLUDE_DIR)
-- Could NOT find PortAudio (missing: PORTAUDIO_LIBRARY PORTAUDIO_INCLUDE_DIR)
-- Could NOT find PulseAudio (missing: PULSEAUDIO_LIBRARY PULSEAUDIO_INCLUDE_DIR)
-- Could NOT find JACK (missing: JACK_LIBRARY JACK_INCLUDE_DIR)
-- Looking for include files SLES/OpenSLES.h, SLES/OpenSLES_Android.h
-- Looking for include files SLES/OpenSLES.h, SLES/OpenSLES_Android.h - not found
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
-- Found Git: /Users/hoechenberger/miniconda3/envs/conda-build/bin/git (found version "2.22.0")
CMake Warning at utils/alsoft-config/CMakeLists.txt:15 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


-- Found unsuitable Qt version "" from NOTFOUND
-- Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
--
-- Building OpenAL with support for the following backends:
--      CoreAudio, WaveFile, Null
--
-- Building with support for CPU extensions:
--     Default, SSE, SSE2, SSE3, SSE4.1
--
-- Embedding HRTF datasets
--
-- Installing sample configuration
--
-- Installing HRTF definitions
--
-- Installing AmbDec presets
--
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11")
-- Could NOT find MYSOFA (missing: MYSOFA_LIBRARY MYSOFA_INCLUDE_DIR)
-- Building utility programs
--
-- Building test programs
--
-- Building example programs
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hoechenberger/Development/openal-soft/build
```
</details>

**Comment by kcat** [comment]
That's really odd. The `-std=c11` switch works, and it is finding `aligned_alloc`, so C11 is supported. I don't know why it would fail during actually compiling, then. Unless it does something silly like go out of its way to hide C11 stuff for C++ code despite actually supporting it.

**Comment by qwertychouskie** [comment]
It seems the code needs to be defined as C++17: https://stackoverflow.com/a/29247842

**Comment by kcat** [comment]
Then it is indeed doing something silly. The compiler and system supports C11 and `aligned_alloc`, but because C++11 hadn't standardized it, the function is purposely hidden. Wonder if that means `posix_memalign` is also purposely hidden since that's not C++11 standard either.

**Comment by hoechenberger** [comment]
I realized I ran the above code while a conda environment was activated — maybe there’s an interference right there. I will try again later today with the environment disabled, and report back!

**Comment by hoechenberger** [comment]
> I will try again later today with the environment disabled

Same results. Tried with `cmake` installed via `homebrew`.

**Comment by hoechenberger** [comment]
Any suggestions on how to proceed with this? I'm pretty much clueless, but willing to help! :)

**Comment by qwertychouskie** [comment]
On lines 130-132 of `CMakeLists.txt`, change the all instances of `11` to `17`.  This should (in theory) fix it.

**Comment by kcat** [comment]
Unfortunately I'm not sure the proper way to fix it. OpenAL Soft currently only requires C++11, and since `CHECK_SYMBOL_EXISTS` succeeds for `aligned_alloc`, it assumes it's available. I don't know what macOS expects here. CMake (as with most build systems) doesn't have that strong of a distinction between C and C++, with most checks being done with C and a presumption that C++ would support the same things.

**Comment by hoechenberger** [comment]
@qwertychouskie's suggestion actually fixes the build for me.

However, I now run into an issue apparently related to linking:
```
$ ./alrecord                                                                                                                  (master✱) 
dyld: Symbol not found: __ZTISt8bad_cast
  Referenced from: /Users/hoechenberger/Development/openal-soft/build/libopenal.1.dylib
  Expected in: /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
 in /Users/hoechenberger/Development/openal-soft/build/libopenal.1.dylib
[1]    34707 abort      ./alrecord
```

Only related issue I could find online is https://stackoverflow.com/q/56455562/1944216, but this seems to be caused by the new (beta) SDK which I'm not using.

**Comment by past-due** [comment]
> Unfortunately I'm not sure the proper way to fix it. OpenAL Soft currently only requires C++11, and since `CHECK_SYMBOL_EXISTS` succeeds for `aligned_alloc`, it assumes it's available. I don't know what macOS expects here. CMake (as with most build systems) doesn't have that strong of a distinction between C and C++, with most checks being done with C and a presumption that C++ would support the same things.

@kcat: It should be possible to use [`CHECK_CXX_SYMBOL_EXISTS`](https://cmake.org/cmake/help/latest/module/CheckCXXSymbolExists.html) instead of `CHECK_SYMBOL_EXISTS`.

**Comment by kcat** [comment]
That doesn't look like it would work for `std::aligned_alloc` as C++17 has it, and would also mean it doesn't check if it would be available in C (don't know why it wouldn't be if C++ has it, but then, I don't know why it wouldn't be available in C++ if it is in C on the same system).

Either way, the original issue should be fixed now with commit 7cfb353334c725b3f57a4a2951b4ff9e352fc956. This means it probably won't use `aligned_alloc` even when it otherwise could, and fall back to `posix_memalign` or manual `malloc`+offset alignment, but it should make macOS happy.

**Comment by manhnt9** [comment]
Try 1.19.1 (maybe you're on master?), this version works fine for me on MacOS.

**Comment by kcat** [comment]
Closing as fixed with the aforementioned commit. If there's still an issue, let me know and I'll reopen as needed.
