### ISSUE TITLE
Regression on macOS: linking failure: Undefined symbols "___ulock_wait", "___ulock_wake"

### ISSUE THREAD

**Issue by barracuda156** [kcat/openal-soft#1272]
```
[ 97%] Linking CXX shared library libopenal.dylib
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/OpenAL.dir/link.txt --verbose=ON
Undefined symbols for architecture ppc:
  "___ulock_wait", referenced from:
      (anonymous namespace)::EventThread(gsl::not_null<al::Context*>) in event.cpp.o
      (anonymous namespace)::EventThread(gsl::not_null<al::Context*>) in event.cpp.o
  "___ulock_wake", referenced from:
      StopEventThrd(al::Context*) in event.cpp.o
      StopEventThrd(al::Context*) in event.cpp.o
      void al::atomic_notify_all<unsigned int>(std::atomic<unsigned int>&) in alu.cpp.o
      void al::atomic_notify_all<unsigned int>(std::atomic<unsigned int>&) in alu.cpp.o
      StopEventThrd(al::Context*) in event.cpp.o
      void al::atomic_notify_all<unsigned int>(std::atomic<unsigned int>&) in alu.cpp.o
ld: symbol(s) not found for architecture ppc
collect2: error: ld returned 1 exit status
```

**Comment by barracuda156** [comment]
@kcat Could you please take a look? Commit https://github.com/kcat/openal-soft/commit/ade218b4f7cea1ebde5a17133d7b01af41acff5b claims to address that, but it does not work correctly.

**Comment by barracuda156** [comment]
Turned out, just removing the fallback was enough to fix the build on 10.6.

**Comment by kcat** [comment]
`___ulock_wait` and `___ulock_wake` are declared as weak imports, which shouldn't require those symbols exist at link-time (or run-time). [These old tech notes](https://developer.apple.com/library/archive/technotes/tn2064/_index.html) say the attribute is supported since GCC 3.1 on Mac OS X, so I don't know why it would cause an error like that.

**Comment by barracuda156** [comment]
@kcat It seems to follow from docs that it should work, but apparently it does not, for w/e reason. I never used this attribute myself and don’t recall encountering it, so can’t say for sure.

However, the code without fallbacks compiles fine (with no extra changes in that header besides deleting those). Is it only needed for clangs or for libc++?

**Comment by kcat** [comment]
It's needed when `std::atomic::wait` and friends aren't supported, which is used to prevent the background event processing thread to go into a busy-wait loop and push the CPU to 100% utilization when waiting for something to process.

Since you seem to be building with GCC and glibc, I might be able to reorder which methods to prioritize and try `std::atomic::wait` first, if glibc supports it on older Mac versions. But if it doesn't, it needs weak linking to work to be able to tell whether `__ulock_wait` is available or if the manual fallback is required.

**Comment by barracuda156** [comment]
I did not test functionality, but at least with a modern gcc (and its `libstdc++`) the build links fine and executables can run if fallbacks are removed. `std::atomic::wait` is a feature of C++20? If so, it should work out of the box with any recent gcc, regardless of macOS version.

**Comment by kcat** [comment]
The latest commit may handle this better, though I can't test it. If `std::atomic::wait` is available, it should be used regardless of the target platform, instead of assuming they aren't available on older macOS and trying `__ulock_wait` and `__ulock_wake`.
