### ISSUE TITLE
error: inline declaration of 'configValue<...>' follows non-inline definition

### ISSUE THREAD

**Issue by ryandesign** [kcat/openal-soft#703]
Hello,

openal-soft 1.22.0 doesn't build with Apple LLVM 8.0.0 (clang-800.0.42.1) from Xcode 8.2.1 on OS X 10.11.6. The error is:

```
alc/device.h:150:45: error: inline declaration of 'configValue<std::__1::basic_string<char> >' follows non-inline definition
inline al::optional<std::string> ALCdevice::configValue(const char *block, const char *key)
                                            ^
alc/device.h:150:45: note: previous definition is here
alc/device.h:153:37: error: inline declaration of 'configValue<int>' follows non-inline definition
inline al::optional<int> ALCdevice::configValue(const char *block, const char *key)
                                    ^
alc/device.h:153:37: note: previous definition is here
alc/device.h:156:38: error: inline declaration of 'configValue<unsigned int>' follows non-inline definition
inline al::optional<uint> ALCdevice::configValue(const char *block, const char *key)
                                     ^
alc/device.h:156:38: note: previous definition is here
alc/device.h:159:39: error: inline declaration of 'configValue<float>' follows non-inline definition
inline al::optional<float> ALCdevice::configValue(const char *block, const char *key)
                                      ^
alc/device.h:159:39: note: previous definition is here
alc/device.h:162:38: error: inline declaration of 'configValue<bool>' follows non-inline definition
inline al::optional<bool> ALCdevice::configValue(const char *block, const char *key)
                                     ^
alc/device.h:162:38: note: previous definition is here
```

This was reported to MacPorts here: https://trac.macports.org/ticket/65175

I think the problem may have been introduced here: 9a7bca1116e7676b92ad6a5f33c0adce8172d0b2

A previous similar error was reported and fixed here: #512

**Comment by kcat** [comment]
Should be fixed wit commit 0a57ebdd495149156736aea3e1aba4d2b3e55dd4.

**Comment by ryandesign** [comment]
I applied that change on top of 1.22.0 and it still failed with the same error. Here's the build log:

https://build.macports.org/builders/ports-10.11_x86_64-builder/builds/182024/steps/install-port/logs/stdio

**Comment by ryandesign** [comment]
> I can't get Clang 13 to throw the same error

I should have mentioned that Apple clang 9 and later build this code just fine. It's only Apple clang 8 that sees this error. I am not in a position to know whether this constitutes a compiler bug or simply a valid difference in the way that the developer of Apple clang had interpreted the specifications at the time of Apple clang 8's release and maybe they changed their minds or the specifications were clarified by the time of the release of Apple clang 9. Apple clang 8 is the newest version available on OS X 10.11.
