### ISSUE TITLE
OpenAL header issue after updating to 1.24

### ISSUE THREAD

**Issue by brad0** [kcat/openal-soft#1107]
Updating OpenAL to 1.24 on OpenBSD we ran into a build issue with Aleph One and OpenAL.

```
/usr/local/include/AL/alext.h:821:90: error: expected ')'
typedef void (AL_APIENTRY *LPALGENEFFECTSDIRECT)(ALCcontext *context, ALsizei n, \
                ALuint *effects) AL_API_NOEXCEPT17;
                                                                                      \
                ^
../../Source_Files/GameWorld/effects.h:156:28: note: expanded from macro 'effects'
#define effects (EffectList.data())
```

OpenAL should really avoid using variable names in prototypes (or prefix them with _)

**Comment by kcat** [comment]
> OpenAL should really avoid using variable names in prototypes (or prefix them with _)

Better to have them so IDEs can display what the parameters are, which may also align with specification documentation, clarifying it for the developer. Prefixing them with `_` isn't reliable since user code can use `_effects` as much as `effects`, just as it could use `device` or `_values`. Basically anything that doesn't start with a double-underscore or an underscore+capital letter (which are reserved for the compiler/system) is fair game in user code.

This is one of the reasons why macros are discouraged in C++, they're just doing raw text replacement irrespective of context. In cases where they need to be used, it's best to use all capitals and with a proper prefix (and avoid all capitals for non-macro names). And it's then best to define them after including external/third-party headers. But if headers need to worry about names like `effects` being unusable, then nothing is safe.

**Comment by brad0** [comment]
We ended up adding a patch like so to our port as a workaround.

```
Index: Source_Files/GameWorld/effects.h
--- Source_Files/GameWorld/effects.h.orig
+++ Source_Files/GameWorld/effects.h
@@ -40,6 +40,9 @@ Aug 30, 2000 (Loren Petrich):
 	Added stuff for unpacking and packing
 */
 
+// XXX - avoid conflict between effects macro and variable names in prototypes
+#include <AL/alext.h>
+
 // LP addition:
 #include "dynamic_limits.h"
```

**Comment by brad0** [comment]
This was fixed downstream.

https://github.com/Aleph-One-Marathon/alephone/commit/49f1d867b5fd946d9cbe37d0ca30781665dd7fd7
