### ISSUE TITLE
Clang 23 still doesn't like latest commits

### ISSUE THREAD

**Issue by solbjorn** [kcat/openal-soft#1315]
https://github.com/kcat/openal-soft/commit/75a0d1beb33fc4b28a6262f737d764167c216a44

<details>
<summary>Compiler errors</summary>

```
openal-soft\al\effects\compressor.cpp(107,30): error : explicit specialization of 'commit' after instantiation
    107 | auto EaxCompressorCommitter::commit(const EAXAGCCOMPRESSORPROPERTIES &props) const -> bool
        |                              ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\compressor.cpp(119,30): error : explicit specialization of 'SetDefaults' after instantiation
    119 | void EaxCompressorCommitter::SetDefaults(EaxEffectProps &props)
        |                              ^
  openal-soft\al/eax/effect.h(231,67): note: implicit instantiation first required here
    231 |         case AL_EFFECT_COMPRESSOR: return EaxCompressorCommitter::SetDefaults(props);
        |                                                                   ^
openal-soft\al\effects\compressor.cpp(125,30): error : explicit specialization of 'Get' after instantiation
    125 | void EaxCompressorCommitter::Get(const EaxCall &call, const EAXAGCCOMPRESSORPROPERTIES &props)
        |                              ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\compressor.cpp(137,30): error : explicit specialization of 'Set' after instantiation
    137 | void EaxCompressorCommitter::Set(const EaxCall &call, EAXAGCCOMPRESSORPROPERTIES &props)
        |                              ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
openal-soft\al\effects\distortion.cpp(192,30): error : explicit specialization of 'commit' after instantiation
    192 | auto EaxDistortionCommitter::commit(const EAXDISTORTIONPROPERTIES &props) const -> bool
        |                              ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\distortion.cpp(209,30): error : explicit specialization of 'SetDefaults' after instantiation
    209 | void EaxDistortionCommitter::SetDefaults(EaxEffectProps &props)
        |                              ^
  openal-soft\al/eax/effect.h(232,67): note: implicit instantiation first required here
    232 |         case AL_EFFECT_DISTORTION: return EaxDistortionCommitter::SetDefaults(props);
        |                                                                   ^
openal-soft\al\effects\distortion.cpp(220,30): error : explicit specialization of 'Get' after instantiation
    220 | void EaxDistortionCommitter::Get(const EaxCall &call, const EAXDISTORTIONPROPERTIES &props)
        |                              ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\distortion.cpp(236,30): error : explicit specialization of 'Set' after instantiation
    236 | void EaxDistortionCommitter::Set(const EaxCall &call, EAXDISTORTIONPROPERTIES &props)
        |                              ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
openal-soft\al\effects\echo.cpp(191,24): error : explicit specialization of 'commit' after instantiation
    191 | auto EaxEchoCommitter::commit(const EAXECHOPROPERTIES &props) const -> bool
        |                        ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\echo.cpp(208,24): error : explicit specialization of 'SetDefaults' after instantiation
    208 | void EaxEchoCommitter::SetDefaults(EaxEffectProps &props)
        |                        ^
  openal-soft\al/eax/effect.h(233,55): note: implicit instantiation first required here
    233 |         case AL_EFFECT_ECHO: return EaxEchoCommitter::SetDefaults(props);
        |                                                       ^
openal-soft\al\effects\echo.cpp(219,24): error : explicit specialization of 'Get' after instantiation
    219 | void EaxEchoCommitter::Get(const EaxCall &call, const EAXECHOPROPERTIES &props)
        |                        ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\echo.cpp(235,24): error : explicit specialization of 'Set' after instantiation
    235 | void EaxEchoCommitter::Set(const EaxCall &call, EAXECHOPROPERTIES &props)
        |                        ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
openal-soft\al\effects\pshifter.cpp(133,32): error : explicit specialization of 'commit' after instantiation
    133 | auto EaxPitchShifterCommitter::commit(const EAXPITCHSHIFTERPROPERTIES &props) const -> bool
        |                                ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\pshifter.cpp(147,32): error : explicit specialization of 'SetDefaults' after instantiation
    147 | void EaxPitchShifterCommitter::SetDefaults(EaxEffectProps &props)
        |                                ^
  openal-soft\al/eax/effect.h(238,72): note: implicit instantiation first required here
    238 |         case AL_EFFECT_PITCH_SHIFTER: return EaxPitchShifterCommitter::SetDefaults(props);
        |                                                                        ^
openal-soft\al\effects\pshifter.cpp(155,32): error : explicit specialization of 'Get' after instantiation
    155 | void EaxPitchShifterCommitter::Get(const EaxCall &call, const EAXPITCHSHIFTERPROPERTIES &props)
        |                                ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\pshifter.cpp(168,32): error : explicit specialization of 'Set' after instantiation
    168 | void EaxPitchShifterCommitter::Set(const EaxCall &call, EAXPITCHSHIFTERPROPERTIES &props)
        |                                ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
openal-soft\al\effects\equalizer.cpp(290,29): error : explicit specialization of 'commit' after instantiation
    290 | auto EaxEqualizerCommitter::commit(const EAXEQUALIZERPROPERTIES &props) const -> bool
        |                             ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\equalizer.cpp(312,29): error : explicit specialization of 'SetDefaults' after instantiation
    312 | void EaxEqualizerCommitter::SetDefaults(EaxEffectProps &props)
        |                             ^
  openal-soft\al/eax/effect.h(234,65): note: implicit instantiation first required here
    234 |         case AL_EFFECT_EQUALIZER: return EaxEqualizerCommitter::SetDefaults(props);
        |                                                                 ^
openal-soft\al\effects\equalizer.cpp(328,29): error : explicit specialization of 'Get' after instantiation
    328 | void EaxEqualizerCommitter::Get(const EaxCall &call, const EAXEQUALIZERPROPERTIES &props)
        |                             ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\equalizer.cpp(349,29): error : explicit specialization of 'Set' after instantiation
    349 | void EaxEqualizerCommitter::Set(const EaxCall &call, EAXEQUALIZERPROPERTIES &props)
        |                             ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
openal-soft\al\effects\autowah.cpp(172,27): error : explicit specialization of 'commit' after instantiation
    172 | auto EaxAutowahCommitter::commit(const EAXAUTOWAHPROPERTIES &props) const -> bool
        |                           ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\autowah.cpp(188,27): error : explicit specialization of 'SetDefaults' after instantiation
    188 | void EaxAutowahCommitter::SetDefaults(EaxEffectProps &props)
        |                           ^
  openal-soft\al/eax/effect.h(230,61): note: implicit instantiation first required here
    230 |         case AL_EFFECT_AUTOWAH: return EaxAutowahCommitter::SetDefaults(props);
        |                                                             ^
openal-soft\al\effects\autowah.cpp(198,27): error : explicit specialization of 'Get' after instantiation
    198 | void EaxAutowahCommitter::Get(const EaxCall &call, const EAXAUTOWAHPROPERTIES &props)
        |                           ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\autowah.cpp(213,27): error : explicit specialization of 'Set' after instantiation
    213 | void EaxAutowahCommitter::Set(const EaxCall &call, EAXAUTOWAHPROPERTIES &props)
        |                           ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
openal-soft\al\effects\fshifter.cpp(200,36): error : explicit specialization of 'commit' after instantiation
    200 | auto EaxFrequencyShifterCommitter::commit(const EAXFREQUENCYSHIFTERPROPERTIES &props) const -> bool
        |                                    ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\fshifter.cpp(226,36): error : explicit specialization of 'SetDefaults' after instantiation
    226 | void EaxFrequencyShifterCommitter::SetDefaults(EaxEffectProps &props)
        |                                    ^
  openal-soft\al/eax/effect.h(236,80): note: implicit instantiation first required here
    236 |         case AL_EFFECT_FREQUENCY_SHIFTER: return EaxFrequencyShifterCommitter::SetDefaults(props);
        |                                                                                ^
openal-soft\al\effects\fshifter.cpp(235,36): error : explicit specialization of 'Get' after instantiation
    235 | void EaxFrequencyShifterCommitter::Get(const EaxCall &call, const EAXFREQUENCYSHIFTERPROPERTIES &props)
        |                                    ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\fshifter.cpp(249,36): error : explicit specialization of 'Set' after instantiation
    249 | void EaxFrequencyShifterCommitter::Set(const EaxCall &call, EAXFREQUENCYSHIFTERPROPERTIES &props)
        |                                    ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
openal-soft\al\effects\modulator.cpp(202,29): error : explicit specialization of 'commit' after instantiation
    202 | auto EaxModulatorCommitter::commit(const EAXRINGMODULATORPROPERTIES &props) const -> bool
        |                             ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\modulator.cpp(229,29): error : explicit specialization of 'SetDefaults' after instantiation
    229 | void EaxModulatorCommitter::SetDefaults(EaxEffectProps &props)
        |                             ^
  openal-soft\al/eax/effect.h(237,70): note: implicit instantiation first required here
    237 |         case AL_EFFECT_RING_MODULATOR: return EaxModulatorCommitter::SetDefaults(props);
        |                                                                      ^
openal-soft\al\effects\modulator.cpp(238,29): error : explicit specialization of 'Get' after instantiation
    238 | void EaxModulatorCommitter::Get(const EaxCall &call, const EAXRINGMODULATORPROPERTIES &props)
        |                             ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\modulator.cpp(252,29): error : explicit specialization of 'Set' after instantiation
    252 | void EaxModulatorCommitter::Set(const EaxCall &call, EAXRINGMODULATORPROPERTIES &props)
        |                             ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
openal-soft\al\effects\null.cpp(88,24): error : explicit specialization of 'commit' after instantiation
     88 | auto EaxNullCommitter::commit(const std::monostate &props) const -> bool
        |                        ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\null.cpp(97,24): error : explicit specialization of 'SetDefaults' after instantiation
     97 | void EaxNullCommitter::SetDefaults(EaxEffectProps &props)
        |                        ^
  openal-soft\al/eax/effect.h(242,34): note: implicit instantiation first required here
    242 |         return EaxNullCommitter::SetDefaults(props);
        |                                  ^
openal-soft\al\effects\null.cpp(103,24): error : explicit specialization of 'Get' after instantiation
    103 | void EaxNullCommitter::Get(const EaxCall &call, const std::monostate&)
        |                        ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\null.cpp(110,24): error : explicit specialization of 'Set' after instantiation
    110 | void EaxNullCommitter::Set(const EaxCall &call, std::monostate&)
        |                        ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
openal-soft\al\effects\chorus.cpp(541,26): error : explicit specialization of 'commit' after instantiation
    541 | auto EaxChorusCommitter::commit(const EAXCHORUSPROPERTIES &props) const -> bool
        |                          ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\chorus.cpp(548,26): error : explicit specialization of 'SetDefaults' after instantiation
    548 | void EaxChorusCommitter::SetDefaults(EaxEffectProps &props)
        |                          ^
  openal-soft\al/eax/effect.h(229,59): note: implicit instantiation first required here
    229 |         case AL_EFFECT_CHORUS: return EaxChorusCommitter::SetDefaults(props);
        |                                                           ^
openal-soft\al\effects\chorus.cpp(555,26): error : explicit specialization of 'Get' after instantiation
    555 | void EaxChorusCommitter::Get(const EaxCall &call, const EAXCHORUSPROPERTIES &props)
        |                          ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\chorus.cpp(562,26): error : explicit specialization of 'Set' after instantiation
    562 | void EaxChorusCommitter::Set(const EaxCall &call, EAXCHORUSPROPERTIES &props)
        |                          ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
openal-soft\al\effects\chorus.cpp(579,27): error : explicit specialization of 'commit' after instantiation
    579 | auto EaxFlangerCommitter::commit(const EAXFLANGERPROPERTIES &props) const -> bool
        |                           ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\chorus.cpp(586,27): error : explicit specialization of 'SetDefaults' after instantiation
    586 | void EaxFlangerCommitter::SetDefaults(EaxEffectProps &props)
        |                           ^
  openal-soft\al/eax/effect.h(235,61): note: implicit instantiation first required here
    235 |         case AL_EFFECT_FLANGER: return EaxFlangerCommitter::SetDefaults(props);
        |                                                             ^
openal-soft\al\effects\chorus.cpp(593,27): error : explicit specialization of 'Get' after instantiation
    593 | void EaxFlangerCommitter::Get(const EaxCall &call, const EAXFLANGERPROPERTIES &props)
        |                           ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\chorus.cpp(600,27): error : explicit specialization of 'Set' after instantiation
    600 | void EaxFlangerCommitter::Set(const EaxCall &call, EAXFLANGERPROPERTIES &props)
        |                           ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  8 errors generated.
openal-soft\al\effects\vmorpher.cpp(340,32): error : explicit specialization of 'commit' after instantiation
    340 | auto EaxVocalMorpherCommitter::commit(const EAXVOCALMORPHERPROPERTIES &props) const -> bool
        |                                ^
  openal-soft\al/eax/effect.h(316,64): note: implicit instantiation first required here
    316 |             { return CommitterFor<T>{props_, al_effect_props_}.commit(arg); },
        |                                                                ^
openal-soft\al\effects\vmorpher.cpp(410,32): error : explicit specialization of 'SetDefaults' after instantiation
    410 | void EaxVocalMorpherCommitter::SetDefaults(EaxEffectProps &props)
        |                                ^
  openal-soft\al/eax/effect.h(239,72): note: implicit instantiation first required here
    239 |         case AL_EFFECT_VOCAL_MORPHER: return EaxVocalMorpherCommitter::SetDefaults(props);
        |                                                                        ^
openal-soft\al\effects\vmorpher.cpp(422,32): error : explicit specialization of 'Get' after instantiation
    422 | void EaxVocalMorpherCommitter::Get(const EaxCall &call, const EAXVOCALMORPHERPROPERTIES &props)
        |                                ^
  openal-soft\al/eax/effect.h(296,77): note: implicit instantiation first required here
    296 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Get(call, arg); },
        |                                                                             ^
openal-soft\al\effects\vmorpher.cpp(439,32): error : explicit specialization of 'Set' after instantiation
    439 | void EaxVocalMorpherCommitter::Set(const EaxCall &call, EAXVOCALMORPHERPROPERTIES &props)
        |                                ^
  openal-soft\al/eax/effect.h(276,77): note: implicit instantiation first required here
    276 |         return std::visit([&]<typename T>(T &arg) { return CommitterFor<T>::Set(call, arg); },
        |                                                                             ^
  4 errors generated.
```

</details>

**Comment by ambitiuswisdom** [comment]
This is not Clang-specific. MinGW-w64 GCC 16.2.0 fails at commit 75a0d1be with the same “explicit specialization after instantiation” errors in `autowah.cpp`, `chorus.cpp`, and `compressor.cpp`, even with `ALSOFT_ENABLE_MODULES=OFF`. The regression appears related to the EAX committer refactor introduced in 56293ae2 and its follow-up fixes.

**Comment by kcat** [comment]
Commit 91317a4f15fbfd9477b871b0c324c99a2c65dc11 should fix it. It works for me with Clang 21 and GCC 16.2.

**Comment by solbjorn** [comment]
@kcat, works for me. If @ambitiuswisdom also doesn't have issues anymore, feel free to close as completed.

**Comment by ambitiuswisdom** [comment]
Also works for me.
