### ISSUE TITLE
Fails to build with llvm 21.1.0-rc1 due to missing malloc include.

### ISSUE THREAD

**Issue by rorgoroth** [kcat/openal-soft#1156]
Hi,
This build error popped up after updating latest llvm rc.

```llvm
ninja: subcommand failed
[1/105] Generating version_witness.txt
[2/105] Building CXX object fmt-11.1.4/CMakeFiles/alsoft.fmt.dir/src/os.cc.obj
[3/105] Building CXX object fmt-11.1.4/CMakeFiles/alsoft.fmt.dir/src/format.cc.obj
In file included from /home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/src/os.cc:13:
In file included from /home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/os.h:11:
/home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/format.h:747:28: error: use of undeclared identifier 'malloc'
  747 |     T* p = static_cast<T*>(malloc(n * sizeof(T)));
      |                            ^~~~~~
/home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/format.h:752:35: error: call to function 'free' that is neither visible in the template definition nor found by argument-dependent lookup
  752 |   void deallocate(T* p, size_t) { free(p); }
      |                                   ^
/home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/format.h:812:46: note: in instantiation of member function 'fmt::detail::allocator<int>::deallocate' requested here
  812 |     if (old_data != self.store_) self.alloc_.deallocate(old_data, old_capacity);
      |                                              ^
/mingw64/x86_64-w64-mingw32/include/stdlib.h:453:16: note: 'free' should be declared prior to the call site
  453 |   void __cdecl free(void *_Memory);
      |                ^
In file included from /home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/src/os.cc:13:
In file included from /home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/os.h:11:
/home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/format.h:752:35: error: call to function 'free' that is neither visible in the template definition nor found by argument-dependent lookup
  752 |   void deallocate(T* p, size_t) { free(p); }
      |                                   ^
/home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/format.h:812:46: note: in instantiation of member function 'fmt::detail::allocator<char>::deallocate' requested here
  812 |     if (old_data != self.store_) self.alloc_.deallocate(old_data, old_capacity);
      |                                              ^
/mingw64/x86_64-w64-mingw32/include/stdlib.h:453:16: note: 'free' should be declared prior to the call site
  453 |   void __cdecl free(void *_Memory);
      |                ^
In file included from /home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/src/os.cc:13:
In file included from /home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/os.h:11:
/home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/format.h:752:35: error: call to function 'free' that is neither visible in the template definition nor found by argument-dependent lookup
  752 |   void deallocate(T* p, size_t) { free(p); }
      |                                   ^
/home/ray/mingw/build/packages/openal-prefix/src/openal/fmt-11.1.4/include/fmt/format.h:812:46: note: in instantiation of member function 'fmt::detail::allocator<unsigned int>::deallocate' requested here
  812 |     if (old_data != self.store_) self.alloc_.deallocate(old_data, old_capacity);
      |                                              ^
/mingw64/x86_64-w64-mingw32/include/stdlib.h:453:16: note: 'free' should be declared prior to the call site
  453 |   void __cdecl free(void *_Memory);
      |                ^
4 errors generated.
```

I fixed it via:
```llvm
--- a/fmt-11.1.1/include/fmt/format.h   2025-03-29 04:08:24.000000000 +0000
+++ b/fmt-11.1.1/include/fmt/format.h   2025-07-18 08:48:48.008477694 +0100
@@ -41,6 +41,7 @@
 #include "base.h"

 #ifndef FMT_MODULE
+#  include <malloc.h>  // LLVM 21.X.X
 #  include <cmath>    // std::signbit
 #  include <cstddef>  // std::byte
 #  include <cstdint>  // uint32_t
```
Perhaps you would do it differently.
Build error present on both latest release and git master.

Thanks for your time and help.

**Comment by kcat** [comment]
Looks like the correct header is `stdlib.h`/`cstdlib`. Fixed with commit 6b69e11867e6498f244da95de7a3d6c25f79f205.

**Comment by rorgoroth** [comment]
That build and runs fine as far as I can tell.

Thanks again!
