### ISSUE TITLE
compilation fails on ppc64el with Altivec SIMD since 1.24.0

### ISSUE THREAD

**Issue by smcv** [kcat/openal-soft#1061]
Version 1.24.0 doesn't build successfully on Debian's ppc64el (little-endian 64-bit POWER) architecture:

```
/<<PKGBUILDDIR>>/common/pffft.cpp: In function ‘void {anonymous}::uninterleave2(v4sf, v4sf, v4sf&, v4sf&)’:
...
/<<PKGBUILDDIR>>/common/pffft.cpp:130:12: error: ‘tmp’ was not declared in this scope; did you mean ‘tm’?
  130 |     out1 = tmp;
```

I think this is a regression from commit 8032217 "Avoid some unnecessary tmp vars" which looks like there's a mistake in the Altivec implementation. I'll ask the Debian ppc64el/powerpc/ppc64 ports team if they can submit a PR for a fixed, tested Altivec code path.

([Debian bug 1087828](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1087828), [full build log](https://buildd.debian.org/status/fetch.php?pkg=openal-soft&arch=ppc64el&ver=1%3A1.24.0-1&stamp=1731960232&raw=0))

**Comment by kcat** [comment]
Looks like I missed that line that should have been removed. Commit 62b33d388685a8feb6505478dd497c392110884d should fix it.

**Comment by jbicha** [comment]
Yes, that [fixed](https://buildd.debian.org/status/package.php?p=openal-soft) this issue
