### ISSUE TITLE
fatal error: 'filesystem' file not found

### ISSUE THREAD

**Issue by ryandesign** [kcat/openal-soft#1065]
openal-soft 1.24.0 doesn't build on macOS 10.14 or earlier:

```
utils/makemhr/loaddef.cpp:33:10: fatal error: 'filesystem' file not found
#include <filesystem>
         ^~~~~~~~~~~~
```

Full build log: https://build.macports.org/builders/ports-10.14_x86_64-builder/builds/223612/steps/install-port/logs/stdio

It builds on macOS 12 and later.

This is a regression; 1.23.1 didn't have this problem.

`std::filesystem` is part of C++17 but the version of libc++ included with macOS 10.14 and earlier doesn't support it. Compiling with a newer version of clang that supports C++17 is not sufficient.

**Comment by kcat** [comment]
> `std::filesystem` is part of C++17 but the version of libc++ included with macOS 10.14 and earlier doesn't support it. Compiling with a newer version of clang that supports C++17 is not sufficient.

You should be able to static-link libc++. There is the `ALSOFT_STATIC_STDCXX` cmake option to link with `-static-libstdc++`, which the prebuilt Windows binaries use to avoid needing `libstdc++.dll`. According to [this stackoverflow comment](https://stackoverflow.com/questions/71991097/clang-static-libstdc-equivalent-for-libc#comment127209230_71991097), it should work with Clang when using libc++ too (for Clang 14 at least; older versions may need to use a more esoteric command like `-Wl,--push-state,-Bstatic -lc++ -lc++abi -Wl,--pop-state` or something).

**Comment by ryandesign** [comment]
Statically linking with libc++, or any system library, would be highly irregular on macOS. I've never seen that done. The Stack Overflow post you refer to is about Linux, and macOS is very much not Linux. Statically linking with the system libc++ won't accomplish anything anyway since it doesn't support `std::filesystem` so really what you're suggesting is that I should link (statically or dynamically) with a newer libc++ that does support `std::filesystem`, and that may indeed work; I have not tried yet.

I don't know the consequences of doing so. For example, if openal-soft is using a newer libc++, and a program that uses openal-soft (or one of the other libraries it uses) uses the system's older libc++, does that cause any problems? Such mixing of different C++ libraries within the same address space definitely did cause crashes in the days of Mac OS X 10.6 and earlier when Apple was using libstdc++ from g++ 4.2.1 and we wanted to use a newer libstdc++ from a newer g++ for some software until we discovered that we needed to [define `_GLIBCXX_USE_CXX11_ABI` to `0`](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/libstdc++/manual/manual/using_dual_abi.html) but I don't know if a similar problem occurs when mixing libc++ versions.

**Comment by dpogue** [comment]
Building with a newer compiler version but targeting macOS 10.14 also fails because while the `filesystem` header is available, the implementation is explicitly annotated as not being available until macOS 10.15:

```
openal-soft/src/1.24.1-dd514aebad.clean/core/ambdec.cpp:84:38: error: 'u8path<const char *>' is unavailable: introduced in macOS 10.15
    std::ifstream f{std::filesystem::u8path(fname)};
                                     ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__filesystem/u8path.h:85:5: note: 'u8path<const char *>' has been explicitly marked unavailable here
    u8path(const _Source& __s) {
    ^
openal-soft/src/1.24.1-dd514aebad.clean/core/ambdec.cpp:84:21: error: '~path' is unavailable: introduced in macOS 10.15
    std::ifstream f{std::filesystem::u8path(fname)};
                    ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__filesystem/path.h:509:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
openal-soft/src/1.24.1-dd514aebad.clean/core/ambdec.cpp:84:19: error: 'basic_ifstream' is unavailable: introduced in macOS 10.15
    std::ifstream f{std::filesystem::u8path(fname)};
                  ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/fstream:1170:14: note: 'basic_ifstream' has been explicitly marked unavailable here
    explicit basic_ifstream(const filesystem::path& __p, ios_base::openmode __mode = ios_base::in)
             ^
3 errors generated.
```

**Comment by dpogue** [comment]
I wonder if using something like https://github.com/gulrak/filesystem to shim the filesystem APIs on systems without built-in support might work

**Comment by dpogue** [comment]
This will break again in a future version as a result of https://github.com/kcat/openal-soft/commit/82b51e9e6d30ae88d26bc2c99782ad7d17ae8ba0 which makes it impossible to build OpenAL-Soft for macOS 10.14 or earlier

**Comment by kcat** [comment]
> This will break again in a future version as a result of [82b51e9](https://github.com/kcat/openal-soft/commit/82b51e9e6d30ae88d26bc2c99782ad7d17ae8ba0) which makes it impossible to build OpenAL-Soft for macOS 10.14 or earlier

Even with the move to C++20?

**Comment by dpogue** [comment]
> Even with the move to C++20?

It won't matter, because the standard library on macOS is provided by libSystem which is part of the operating system. The macOS header files are annotated to indicate that std::filesystem is not available on versions below macOS 10.15.

**Comment by kcat** [comment]
I reverted it, though I'm not sure versions before 10.15 still work.
